-- Migration 0001: tables ported ~1:1 from Xano (generated from xano-tables-schema.json 2026-07-30)
-- Types: int->bigint, decimal->numeric, timestamp->timestamptz, json/attachment->jsonb; fixes: clients.abn/postcode -> text

create table if not exists audio_site (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text,
  site text
);
create index if not exists idx_audio_site_created_at on audio_site (created_at);

create table if not exists bvod_site (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text,
  site text
);
create index if not exists idx_bvod_site_created_at on bvod_site (created_at);

create table if not exists campaign_kpi (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mp_client_name text,
  mba_number text,
  version_number bigint,
  campaign_name text,
  media_type text,
  publisher text,
  bid_strategy text,
  ctr numeric,
  cpv numeric,
  conversion_rate numeric,
  vtr numeric,
  frequency numeric,
  line_item_id text
);
create index if not exists idx_campaign_kpi_created_at on campaign_kpi (created_at);

create table if not exists client_domains (
  id bigint generated by default as identity primary key,
  client_id bigint,
  email_domain text
);
create index if not exists idx_client_domains_client_id on client_domains (client_id);
create index if not exists idx_client_domains_email_domain on client_domains (email_domain);

create table if not exists client_kpi (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mp_client_name text,
  publisher_name text,
  media_type text,
  bid_strategy text,
  ctr numeric,
  cpv numeric,
  conversion_rate numeric,
  vtr numeric,
  frequency numeric
);
create index if not exists idx_client_kpi_created_at on client_kpi (created_at);

create table if not exists client_notes (
  id bigint generated by default as identity primary key,
  client_id bigint,
  mba_number text,
  source text,
  title text,
  body text,
  meeting_date timestamptz,
  fireflies_meeting_id text,
  participants text,
  created_at timestamptz not null default now()
);
create index if not exists idx_client_notes_client_id on client_notes (client_id);
create unique index if not exists idx_client_notes_fireflies_meeting_id on client_notes (fireflies_meeting_id);

create table if not exists clientdashboard (
  id bigint generated by default as identity primary key,
  Client_dashboard text,
  idgoogleads_dashboard text,
  idmeta_dashboard text,
  idcm360_dashboard text,
  iddv360_dashboard text,
  idtiktok_dashboard text,
  idlinkedin_dashboard text,
  idpinterest_dashboard text,
  idquantcast_dashboard text,
  idtaboola_dashboard text,
  idsnapchat_dashboard text,
  idbing_dashboard text,
  idvistar_dashboard text,
  idga4_dashboard text,
  idmerchantcentre_dashboard text,
  idshopify_dashboard text
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  mp_client_name text,
  clientcategory text,
  abn text,
  mbaidentifier text,
  legalbusinessname text,
  streetaddress text,
  suburb text,
  state_dropdown text,
  postcode text,
  keyfirstname text,
  keylastname text,
  keyphone bigint,
  keyemail text,
  billingfirstname text,
  billinglastname text,
  billingphone bigint,
  billingemail text,
  monthlyretainer numeric,
  organicsocial numeric,
  television_checkbox boolean,
  radio_checkbox boolean,
  newspapers_checkbox boolean,
  magazines_checkbox boolean,
  ooh_checkbox boolean,
  cinema_checkbox boolean,
  digitaldisplay_checkbox boolean,
  digitalaudio_checkbox boolean,
  digitalvideo_checkbox boolean,
  bvod_checkbox boolean,
  feesocial numeric,
  feesearch numeric,
  feeprogdisplay numeric,
  feeprogvideo numeric,
  feeprogbvod numeric,
  feeprogaudio numeric,
  feeprogooh numeric,
  feecontentcreator numeric,
  adservvideo numeric,
  adservimp numeric,
  adservdisplay numeric,
  adservaudio numeric,
  idgoogleads text,
  idmeta text,
  idcm360 text,
  iddv360 text,
  idtiktok text,
  idlinkedin text,
  idpinterest text,
  idquantcast text,
  idtaboola text,
  idsnapchat text,
  idbing text,
  idvistar text,
  idga4 text,
  idmerchantcentre text,
  idshopify text,
  payment_days bigint,
  payment_terms text,
  brand_colour text,
  client_logo jsonb
);

create table if not exists creative_asset (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mba_number text,
  media_plan_master_id bigint,
  line_item_id text,
  source_table text,
  asset_name text,
  original_filename text,
  mime_type text,
  file_size_bytes bigint,
  width_px bigint,
  height_px bigint,
  duration_seconds numeric,
  blob_url text,
  blob_pathname text,
  status text,
  uploaded_by_email text,
  uploaded_by_role text
);
create index if not exists idx_creative_asset_created_at on creative_asset (created_at);
create index if not exists idx_creative_asset_mba_number on creative_asset (mba_number);

create table if not exists display_site (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text,
  site text
);
create index if not exists idx_display_site_created_at on display_site (created_at);

create table if not exists finance_billing_line_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  finance_billing_records_id bigint,
  item_code text,
  line_type text,
  media_type text,
  description text,
  publisher_name text,
  amount numeric,
  client_pays_media boolean,
  sort_order bigint,
  updated_at timestamptz,
  line_item_id text,
  line_status text,
  received_at timestamptz,
  received_amount numeric,
  note text,
  orphaned boolean,
  media_plan_version_number bigint
);
create index if not exists idx_finance_billing_line_items_created_at on finance_billing_line_items (created_at);
create index if not exists idx_finance_billing_line_items_finance_billing_records_id_line_item_id on finance_billing_line_items (finance_billing_records_id, line_item_id);

create table if not exists finance_billing_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clients_id bigint,
  client_name text,
  billing_type text,
  mba_number text,
  campaign_name text,
  po_number text,
  billing_month text,
  invoice_date date,
  payment_days bigint,
  payment_terms text,
  status text,
  total numeric,
  has_pending_edits boolean,
  source_billing_schedule_id bigint,
  updated_at timestamptz,
  billed boolean,
  billed_at timestamptz,
  billed_by bigint,
  notes text,
  exported_at timestamptz,
  exported_by bigint,
  invoice_key text
);
create index if not exists idx_finance_billing_records_created_at on finance_billing_records (created_at);
create unique index if not exists idx_finance_billing_records_invoice_key on finance_billing_records (invoice_key);

create table if not exists finance_edits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  finance_billing_records_id bigint,
  finance_billing_line_items_id bigint,
  edit_type text,
  field_name text,
  old_value text,
  new_value text,
  edit_status text,
  edited_by bigint,
  edited_by_name text,
  published_at timestamptz,
  record_type text
);
create index if not exists idx_finance_edits_created_at on finance_edits (created_at);

create table if not exists finance_saved_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint, -- was "user" in Xano (reserved word in Postgres); ETL maps user -> user_id
  view_name text,
  filters jsonb,
  is_default boolean,
  updated_at timestamptz
);
create index if not exists idx_finance_saved_views_created_at on finance_saved_views (created_at);

create table if not exists magazines (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  network text,
  title text
);
create index if not exists idx_magazines_created_at on magazines (created_at);

create table if not exists magazines_adsizes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  adsize text
);
create index if not exists idx_magazines_adsizes_created_at on magazines_adsizes (created_at);

create table if not exists media_container_best_practice (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  media_container text,
  best_practice jsonb,
  is_active boolean,
  _name text
);
create unique index if not exists idx_media_container_best_practice_media_container on media_container_best_practice (media_container);

create table if not exists newspaper_adsizes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  adsize text
);
create index if not exists idx_newspaper_adsizes_created_at on newspaper_adsizes (created_at);

create table if not exists newspapers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  network text,
  title text
);
create index if not exists idx_newspapers_created_at on newspapers (created_at);

create table if not exists pacing_orphan_fixes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  admin_user_email text,
  channel text,
  platform_line_item_id text,
  previous_line_item_id text,
  new_line_item_id text,
  ad_group_name text,
  campaign_name text,
  note text
);

create table if not exists planning_audiences (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clients_id bigint,
  mba_number text,
  name text,
  definition_json jsonb,
  composed_wc numeric,
  client_visible boolean,
  created_by_email text
);
create index if not exists idx_planning_audiences_clients_id on planning_audiences (clients_id);
create index if not exists idx_planning_audiences_mba_number on planning_audiences (mba_number);

create table if not exists publisher_kpi (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  publisher text,
  bid_strategy text,
  ctr numeric,
  cpv numeric,
  conversion_rate numeric,
  vtr numeric,
  frequency numeric,
  media_type text
);
create index if not exists idx_publisher_kpi_created_at on publisher_kpi (created_at);

create table if not exists publishers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  publisher_name text,
  publisherid text,
  publishertype text,
  billingagency text,
  financecode text,
  pub_television boolean,
  pub_radio boolean,
  pub_newspaper boolean,
  pub_magazines boolean,
  pub_ooh boolean,
  pub_cinema boolean,
  pub_digidisplay boolean,
  pub_digiaudio boolean,
  pub_digivideo boolean,
  pub_bvod boolean,
  pub_integration boolean,
  pub_search boolean,
  pub_socialmedia boolean,
  pub_progdisplay boolean,
  pub_progvideo boolean,
  pub_progbvod boolean,
  pub_progaudio boolean,
  pub_progooh boolean,
  pub_influencers boolean,
  radio_comms numeric,
  newspaper_comms numeric,
  television_comms numeric,
  magazines_comms numeric,
  ooh_comms numeric,
  cinema_comms numeric,
  digidisplay_comms numeric,
  digiaudio_comms numeric,
  digivideo_comms numeric,
  bvod_comms numeric,
  integration_comms numeric,
  search_comms numeric,
  progdisplay_comms numeric,
  progvideo_comms numeric,
  progbvod_comms numeric,
  progaudio_comms numeric,
  progooh_comms numeric,
  influencers_comms numeric,
  digitaldisplay_cpm_default numeric,
  digitaldisplay_cpc_default numeric,
  digitaldisplay_cpv_default numeric,
  digitaldisplay_ctr_default numeric,
  digitaldisplay_vtr_default numeric,
  digitaldisplay_frequency_default numeric,
  digitalvideo_cpm_default numeric,
  digitalvideo_cpc_default numeric,
  digitalvideo_cpv_default numeric,
  digitalvideo_ctr_default numeric,
  digitalvideo_vtr_default numeric,
  digitalvideo_frequency_default numeric,
  digitalaudio_cpm_default numeric,
  digitalaudio_cpc_default numeric,
  digitalaudio_cpv_default numeric,
  digitalaudio_ctr_default numeric,
  digitalaudio_vtr_default numeric,
  digitalaudio_frequency_default numeric,
  bvod_cpm_default numeric,
  bvod_cpc_default numeric,
  bvod_cpv_default numeric,
  bvod_ctr_default numeric,
  bvod_vtr_default numeric,
  bvod_frequency_default numeric,
  search_cpm_default numeric,
  search_cpc_default numeric,
  search_cpv_default numeric,
  search_ctr_default numeric,
  search_vtr_default numeric,
  search_frequency_default numeric,
  socialmedia_cpm_default numeric,
  socialmedia_cpc_default numeric,
  socialmedia_cpv_default numeric,
  socialmedia_ctr_default numeric,
  socialmedia_vtr_default numeric,
  socialmedia_frequency_default numeric,
  progdisplay_cpm_default numeric,
  progdisplay_cpc_default numeric,
  progdisplay_cpv_default numeric,
  progdisplay_ctr_default numeric,
  progdisplay_vtr_default numeric,
  progdisplay_frequency_default numeric,
  progvideo_cpm_default numeric,
  progvideo_cpc_default numeric,
  progvideo_cpv_default numeric,
  progvideo_ctr_default numeric,
  progvideo_vtr_default numeric,
  progvideo_frequency_default numeric,
  progbvod_cpm_default numeric,
  progbvod_cpc_default numeric,
  progbvod_cpv_default numeric,
  progbvod_ctr_default numeric,
  progbvod_vtr_default numeric,
  progbvod_frequency_default numeric,
  progaudio_cpm_default numeric,
  progaudio_cpc_default numeric,
  progaudio_cpv_default numeric,
  progaudio_ctr_default numeric,
  progaudio_vtr_default numeric,
  progaudio_frequency_default numeric,
  publisher_colour text,
  best_practice jsonb
);

create table if not exists radio_stations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  station text,
  network text
);
create index if not exists idx_radio_stations_created_at on radio_stations (created_at);

create table if not exists revenue_forecast_lines (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clients_id bigint,
  fy text,
  line_key text,
  month text,
  amount numeric,
  updated_by text,
  updated_at timestamptz
);
create index if not exists idx_revenue_forecast_lines_clients_id on revenue_forecast_lines (clients_id);
create index if not exists idx_revenue_forecast_lines_fy on revenue_forecast_lines (fy);

create table if not exists revenue_line_catalog (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  line_key text,
  label text,
  fee_pct numeric,
  booked_mapping jsonb,
  sort_order bigint,
  active boolean
);
create unique index if not exists idx_revenue_line_catalog_line_key on revenue_line_catalog (line_key);

create table if not exists scope_of_work (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_name text,
  contact_name text,
  contact_email text,
  scope_date date,
  scope_version bigint,
  project_name text,
  project_status text,
  project_overview text,
  deliverables text,
  tasks_steps text,
  timelines text,
  responsibilities text,
  requirements text,
  assumptions text,
  exclusions text,
  cost jsonb,
  payment_terms_and_conditions text,
  scope_id text,
  billing_schedule jsonb
);
create index if not exists idx_scope_of_work_created_at on scope_of_work (created_at);

create table if not exists task_checklist_items (
  id bigint generated by default as identity primary key,
  task_id bigint,
  label text,
  done boolean,
  sort bigint
);
create index if not exists idx_task_checklist_items_task_id on task_checklist_items (task_id);

create table if not exists task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint,
  user_id bigint,
  body text,
  created_at timestamptz not null default now()
);
create index if not exists idx_task_comments_task_id on task_comments (task_id);

create table if not exists task_template_items (
  id bigint generated by default as identity primary key,
  template_id bigint,
  label text,
  sort bigint
);
create index if not exists idx_task_template_items_template_id on task_template_items (template_id);

create table if not exists task_templates (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  client_id bigint,
  mba_number text,
  title text,
  description text,
  status text,
  priority text,
  assignee_user_id bigint,
  due_date timestamptz,
  recurring_rule text,
  template_id bigint,
  client_visible boolean,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create index if not exists idx_tasks_client_id_status on tasks (client_id, status);
create index if not exists idx_tasks_assignee_user_id_due_date on tasks (assignee_user_id, due_date);

create table if not exists tv_stations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  network text,
  station text
);
create index if not exists idx_tv_stations_created_at on tv_stations (created_at);

create table if not exists video_site (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text,
  site text
);
create index if not exists idx_video_site_created_at on video_site (created_at);

create table if not exists xero_ap_bills (
  id bigint generated by default as identity primary key,
  xero_invoice_id text,
  invoice_number text,
  xero_contact_id text,
  status text,
  sub_total numeric,
  total_tax numeric,
  total numeric,
  amount_paid numeric,
  amount_due numeric,
  currency text,
  issue_date date,
  due_date date,
  fully_paid_date date,
  activity_month date,
  reference_raw text,
  line_items_json jsonb,
  pdf_file jsonb,
  xero_updated_utc timestamptz,
  last_synced_at timestamptz,
  raw_json jsonb
);
create unique index if not exists idx_xero_ap_bills_xero_invoice_id on xero_ap_bills (xero_invoice_id);

create table if not exists xero_ar_invoices (
  id bigint generated by default as identity primary key,
  xero_invoice_id text,
  invoice_number text,
  xero_contact_id text,
  status text,
  sub_total numeric,
  total_tax numeric,
  total numeric,
  amount_paid numeric,
  amount_due numeric,
  currency text,
  issue_date date,
  due_date date,
  fully_paid_date date,
  reference_raw text,
  mba_number text,
  mba_match_id bigint,
  line_items_json jsonb,
  pdf_file jsonb,
  xero_updated_utc timestamptz,
  last_synced_at timestamptz,
  raw_json jsonb
);
create unique index if not exists idx_xero_ar_invoices_xero_invoice_id on xero_ar_invoices (xero_invoice_id);

create table if not exists xero_contacts (
  id bigint generated by default as identity primary key,
  xero_contact_id text,
  name text,
  role text,
  email text,
  raw_json jsonb,
  synced_at timestamptz
);
create unique index if not exists idx_xero_contacts_xero_contact_id on xero_contacts (xero_contact_id);

create table if not exists xero_sync_exceptions (
  id bigint generated by default as identity primary key,
  xero_invoice_id text,
  invoice_number text,
  reference text,
  reason text,
  raw_json jsonb,
  resolved boolean,
  created_at timestamptz not null default now(),
  issue_date text
);

create table if not exists xero_sync_log (
  id bigint generated by default as identity primary key,
  run_started_at timestamptz,
  run_finished_at timestamptz,
  status text,
  watermark_used timestamptz,
  new_watermark timestamptz,
  invoices_upserted bigint,
  contacts_upserted bigint,
  notes text
);