-- Migration 0002: consolidated plan family (target model per kickoff pack Part B)
-- Run AFTER 0001 (ported tables) — FKs reference clients.

create type line_channel as enum (
  'television','radio','cinema','newspaper','magazines','ooh',
  'prog_display','prog_video','prog_audio','prog_bvod','prog_ooh',
  'digi_display','digi_video','digi_audio','digi_bvod',
  'social','search','influencers','integrations','production'
);
create type schedule_component as enum ('media','fee');
create type schedule_basis as enum ('billing','delivery');
create type schedule_source as enum ('computed','override');

create table if not exists media_plan_masters (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mba_number text not null unique,
  client_id bigint references clients(id),
  mp_client_name text,                          -- legacy convenience during migration; drop post-cutover
  campaign_name text,
  campaign_status text,
  campaign_start_date date,
  campaign_end_date date,
  campaign_budget_cents bigint,
  published_version_id bigint                   -- publish pointer (FK added below, after versions exists)
);

create table if not exists media_plan_versions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  master_id bigint not null references media_plan_masters(id) on delete cascade,
  version_number int not null,
  mba_number text not null,                     -- legacy join key during migration
  campaign_name text,
  campaign_status text,
  campaign_start_date date,
  campaign_end_date date,
  brand text,
  client_contact text,
  po_number text,
  campaign_budget_cents bigint,
  fixed_fee boolean,
  channel_flags jsonb,                          -- the 20 mp_* booleans, keyed by line_channel value
  legacy_schedules jsonb,                       -- {billingSchedule, deliverySchedule} verbatim, audit-only
  media_plan_file jsonb,
  mba_pdf_file jsonb,
  aa_media_plan_file jsonb,
  unique (master_id, version_number)
);

alter table media_plan_masters
  add constraint fk_masters_published_version
  foreign key (published_version_id) references media_plan_versions(id);

create table if not exists line_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  version_id bigint not null references media_plan_versions(id) on delete cascade,
  channel line_channel not null,
  line_item_id text not null,
  position int,
  market text,
  buying_demo text,
  buy_type text,
  publisher text,
  platform text,
  bid_strategy text,
  fixed_cost_media boolean,
  client_pays_for_media boolean,
  budget_includes_fees boolean,
  no_adserving boolean,
  bursts jsonb,                                 -- frozen bursts_json contract shape, verbatim
  attrs jsonb,                                  -- channel-specific tail (station/site/size/duration/...)
  unique (version_id, line_item_id)             -- kills the PENFOLD016 duplication class
);
create index idx_line_items_version on line_items (version_id);
create index idx_line_items_channel on line_items (channel);
create index idx_line_items_line_item_id on line_items (line_item_id);

create table if not exists schedule_months (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  version_id bigint not null references media_plan_versions(id) on delete cascade,
  line_item_id text not null,
  component schedule_component not null,
  basis schedule_basis not null,
  month date not null,                          -- first of month
  amount_cents bigint not null,
  source schedule_source not null default 'computed',
  unique (version_id, line_item_id, component, basis, month)
);
create index idx_schedule_months_version on schedule_months (version_id);
create index idx_schedule_months_month on schedule_months (month);

create table if not exists mba_fee_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  version_id bigint not null unique references media_plan_versions(id) on delete cascade,
  fees jsonb not null,                          -- per-media fee %, adserving rates at approval time
  captured_at timestamptz not null default now()
);

create table if not exists billing_overrides (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  version_id bigint not null references media_plan_versions(id) on delete cascade,
  line_item_id text not null,
  component schedule_component not null,
  mode text default 'manual',
  reason text,
  months jsonb,                                 -- as posted by the app today; folds into schedule_months.source='override'
  date_basis text,
  unique (version_id, line_item_id, component)
);
