-- Migration 0006: xero_client_aliases (T5 Xero sync rebuild)
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke/Claude).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent seed + allowlist extension.
--
-- Deliberate ava_readonly allowlist extension (0003 style): GRANT SELECT + ava_read
-- policy. Future tables stay fail-closed until added the same way.

-- ---------------------------------------------------------------------------
-- 1. Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xero_client_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_key text NOT NULL,
  client_id bigint NOT NULL REFERENCES clients (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_xero_client_aliases_contact_key
  ON xero_client_aliases (contact_key);

ALTER TABLE xero_client_aliases ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 2. ava_readonly allowlist extension
-- ---------------------------------------------------------------------------
GRANT SELECT ON TABLE xero_client_aliases TO ava_readonly;

DROP POLICY IF EXISTS ava_read ON xero_client_aliases;
CREATE POLICY ava_read ON xero_client_aliases
  FOR SELECT TO ava_readonly USING (true);

-- ---------------------------------------------------------------------------
-- 3. Seed known aliases — resolve client_id by mp_client_name; fail loudly
--    contact_key = lower(trim) of the Xero contact name (Xano alias_map keys).
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  missing text;
BEGIN
  SELECT string_agg(v.contact_key || '→' || v.mp_client_name, ', ' ORDER BY v.contact_key)
    INTO missing
  FROM (
    VALUES
      ('hema maps', 'Hema'),
      ('syneron candela corporation australia pty ltd', 'Candela'),
      ('challenger group services ltd', 'Challenger'),
      ('bowel cancer & digestive research institute of australia', 'Bowel Cancer Australia'),
      ('professional golfers association of australia ltd', 'PGA Australia')
  ) AS v(contact_key, mp_client_name)
  LEFT JOIN clients c ON c.mp_client_name = v.mp_client_name
  WHERE c.id IS NULL;

  IF missing IS NOT NULL THEN
    RAISE EXCEPTION
      'xero_client_aliases seed: unresolved mp_client_name for: %',
      missing;
  END IF;

  INSERT INTO xero_client_aliases (contact_key, client_id)
  SELECT v.contact_key, c.id
  FROM (
    VALUES
      ('hema maps', 'Hema'),
      ('syneron candela corporation australia pty ltd', 'Candela'),
      ('challenger group services ltd', 'Challenger'),
      ('bowel cancer & digestive research institute of australia', 'Bowel Cancer Australia'),
      ('professional golfers association of australia ltd', 'PGA Australia')
  ) AS v(contact_key, mp_client_name)
  JOIN clients c ON c.mp_client_name = v.mp_client_name
  ON CONFLICT (contact_key) DO UPDATE
    SET client_id = EXCLUDED.client_id;
END
$$;
