-- Migration 0007: mba_line_approvals (PC0 — Xano port)
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke/Claude).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent; 0003-style ava_readonly allowlist.
--
-- Contract (mirrors live Xano X5.1 table + absence = approved / all-in):
--   rows with approved=false are exclusions; absence of a row ⇒ approved.
-- UNIQUE(mba_number, media_plan_version, line_item_id, media_type).

-- ---------------------------------------------------------------------------
-- 1. Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mba_line_approvals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  mba_number text NOT NULL,
  media_plan_version integer NOT NULL,
  line_item_id text NOT NULL,
  media_type text NOT NULL,
  approved boolean NOT NULL DEFAULT true,
  approved_in_version integer NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mba_line_approvals_mba_ver_line_media
  ON mba_line_approvals (mba_number, media_plan_version, line_item_id, media_type);

CREATE INDEX IF NOT EXISTS idx_mba_line_approvals_mba_version
  ON mba_line_approvals (mba_number, media_plan_version);

CREATE INDEX IF NOT EXISTS idx_mba_line_approvals_line_item_id
  ON mba_line_approvals (line_item_id);

ALTER TABLE mba_line_approvals ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 2. ava_readonly allowlist extension (0003 style)
-- ---------------------------------------------------------------------------
GRANT SELECT ON TABLE mba_line_approvals TO ava_readonly;

DROP POLICY IF EXISTS ava_read ON mba_line_approvals;
CREATE POLICY ava_read ON mba_line_approvals
  FOR SELECT TO ava_readonly USING (true);
