-- Migration 0010: finance_periods + finance_run_items + app_notifications (PC5)
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent.
--
-- Flag: FINANCE_PERIODS=off|shadow|on (default off). First month runs shadow.
-- ava_readonly: SELECT on periods + run_items (Luke-approved); notifications excluded.

-- ---------------------------------------------------------------------------
-- 1. Enums
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE finance_period_status AS ENUM (
    'open',
    'pre_run_review',
    'run',
    'review',
    'locked',
    'invoiced',
    'reconciled'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE finance_run_source AS ENUM ('media', 'retainer', 'sow');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE finance_run_item_status AS ENUM (
    'pending',
    'approved',
    'adjusted',
    'held',
    'excluded',
    'stale'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- 2. clients.retainer_end_month (nullable YYYY-MM-01; $0 monthlyretainer stops)
-- ---------------------------------------------------------------------------
ALTER TABLE clients ADD COLUMN IF NOT EXISTS retainer_end_month date NULL;

-- ---------------------------------------------------------------------------
-- 3. finance_periods
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  period_month date NOT NULL,
  status finance_period_status NOT NULL DEFAULT 'open',
  ran_at timestamptz NULL,
  locked_at timestamptz NULL,
  locked_by text NULL,
  amended_after_lock boolean NOT NULL DEFAULT false,
  sheet_blob_pathname text NULL,
  sheet_version integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_finance_periods_period_month UNIQUE (period_month)
);

CREATE INDEX IF NOT EXISTS idx_finance_periods_status
  ON finance_periods (status);

ALTER TABLE finance_periods ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE finance_periods TO ava_readonly;
DROP POLICY IF EXISTS ava_read ON finance_periods;
CREATE POLICY ava_read ON finance_periods
  FOR SELECT TO ava_readonly USING (true);

-- ---------------------------------------------------------------------------
-- 4. finance_run_items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_run_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  period_id bigint NOT NULL REFERENCES finance_periods(id) ON DELETE CASCADE,
  source finance_run_source NOT NULL,
  natural_key text NOT NULL,
  mba_number text NULL,
  client_id bigint NULL REFERENCES clients(id),
  version_id bigint NULL REFERENCES media_plan_versions(id),
  sow_id bigint NULL,
  line_items_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  amount_cents bigint NOT NULL DEFAULT 0,
  invoice_reference text NOT NULL,
  status finance_run_item_status NOT NULL DEFAULT 'pending',
  adjustment_cents bigint NULL,
  adjustment_reason text NULL,
  hold_reason text NULL,
  exclude_reason text NULL,
  client_snapshot_json jsonb NULL,
  linked_variance_from_item_id bigint NULL REFERENCES finance_run_items(id),
  rolled_from_item_id bigint NULL REFERENCES finance_run_items(id),
  CONSTRAINT uq_finance_run_items_period_source_key
    UNIQUE (period_id, source, natural_key)
);

CREATE INDEX IF NOT EXISTS idx_finance_run_items_period
  ON finance_run_items (period_id);
CREATE INDEX IF NOT EXISTS idx_finance_run_items_status
  ON finance_run_items (status);
CREATE INDEX IF NOT EXISTS idx_finance_run_items_mba
  ON finance_run_items (mba_number);

ALTER TABLE finance_run_items ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE finance_run_items TO ava_readonly;
DROP POLICY IF EXISTS ava_read ON finance_run_items;
CREATE POLICY ava_read ON finance_run_items
  FOR SELECT TO ava_readonly USING (true);

-- ---------------------------------------------------------------------------
-- 5. app_notifications
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  audience text NOT NULL,
  kind text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamptz NULL
);

CREATE INDEX IF NOT EXISTS idx_app_notifications_audience_created
  ON app_notifications (audience, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_notifications_unread
  ON app_notifications (audience)
  WHERE read_at IS NULL;

ALTER TABLE app_notifications ENABLE ROW LEVEL SECURITY;
-- Notifications intentionally NOT granted to ava_readonly (default deny).
