-- Migration 0011: xero_invoice_matches + xero_contact_links (PC6)
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent.
-- Prereq: 0010_finance_periods (finance_run_items) for run_item_id FK.
-- Extends T5 xero-sync; does not fork the pipeline.

-- ---------------------------------------------------------------------------
-- 1. Enums
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE xero_match_method AS ENUM ('reference', 'heuristic', 'manual');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE xero_match_status AS ENUM ('matched', 'diverged', 'disputed', 'written_off');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- 2. xero_contact_links (learned forever from manual assign)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xero_contact_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  xero_contact_key text NOT NULL,
  client_id bigint NOT NULL REFERENCES clients(id),
  learned_from text NULL,
  CONSTRAINT uq_xero_contact_links_key UNIQUE (xero_contact_key)
);

CREATE INDEX IF NOT EXISTS idx_xero_contact_links_client
  ON xero_contact_links (client_id);

ALTER TABLE xero_contact_links ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE xero_contact_links TO ava_readonly;
DROP POLICY IF EXISTS ava_read ON xero_contact_links;
CREATE POLICY ava_read ON xero_contact_links
  FOR SELECT TO ava_readonly USING (true);

-- ---------------------------------------------------------------------------
-- 3. xero_invoice_matches
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xero_invoice_matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  xero_invoice_id text NOT NULL,
  run_item_id bigint NULL REFERENCES finance_run_items(id) ON DELETE SET NULL,
  method xero_match_method NOT NULL,
  confidence numeric(5,4) NOT NULL DEFAULT 0,
  delta_cents bigint NOT NULL DEFAULT 0,
  status xero_match_status NOT NULL DEFAULT 'matched',
  decided_by text NULL,
  decided_at timestamptz NULL,
  card_kind text NULL,
  detail text NULL,
  period_month date NULL,
  CONSTRAINT uq_xero_invoice_matches_invoice UNIQUE (xero_invoice_id)
);

CREATE INDEX IF NOT EXISTS idx_xero_invoice_matches_run_item
  ON xero_invoice_matches (run_item_id);
CREATE INDEX IF NOT EXISTS idx_xero_invoice_matches_status
  ON xero_invoice_matches (status);
CREATE INDEX IF NOT EXISTS idx_xero_invoice_matches_period
  ON xero_invoice_matches (period_month);

ALTER TABLE xero_invoice_matches ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE xero_invoice_matches TO ava_readonly;
DROP POLICY IF EXISTS ava_read ON xero_invoice_matches;
CREATE POLICY ava_read ON xero_invoice_matches
  FOR SELECT TO ava_readonly USING (true);

-- ---------------------------------------------------------------------------
-- 4. Reference hit-rate per month (feeds PC5 pre-run)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xero_match_month_metrics (
  period_month date PRIMARY KEY,
  reference_attempts integer NOT NULL DEFAULT 0,
  reference_hits integer NOT NULL DEFAULT 0,
  reference_hit_rate numeric(7,6) NOT NULL DEFAULT 0,
  tier1_matched integer NOT NULL DEFAULT 0,
  tier1_diverged integer NOT NULL DEFAULT 0,
  tier2_suggested integer NOT NULL DEFAULT 0,
  duplicates integer NOT NULL DEFAULT 0,
  orphans integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE xero_match_month_metrics ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE xero_match_month_metrics TO ava_readonly;
DROP POLICY IF EXISTS ava_read ON xero_match_month_metrics;
CREATE POLICY ava_read ON xero_match_month_metrics
  FOR SELECT TO ava_readonly USING (true);
