-- Migration 0012: plan_working_drafts (PC7)
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent.
-- Flag: NEXT_PUBLIC_PLAN_DRAFTS=on|off (default off) — autosave chrome only.
-- Off retains plan_working_drafts rows; Stage 2b offer + working-draft save stay reachable.
-- Publish path remains savePlanVersion (optional base_version_id stale check always on).

CREATE TABLE IF NOT EXISTS plan_working_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  master_id bigint NOT NULL REFERENCES media_plan_masters(id) ON DELETE CASCADE,
  user_id text NOT NULL,
  user_label text NULL,
  base_version_id bigint NULL REFERENCES media_plan_versions(id) ON DELETE SET NULL,
  draft_state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT uq_plan_working_drafts_master_user UNIQUE (master_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_plan_working_drafts_master
  ON plan_working_drafts (master_id);
CREATE INDEX IF NOT EXISTS idx_plan_working_drafts_updated
  ON plan_working_drafts (updated_at);

ALTER TABLE plan_working_drafts ENABLE ROW LEVEL SECURITY;
-- Not granted to ava_readonly (drafts are editor-private).
