-- 0016_finance_forecast_snapshots.sql
-- AUTHOR ONLY — apply to live Supabase before enabling Finance Forecast snapshot PG writes.
--
-- Mirrors Xano `finance_forecast_snapshots` + `finance_forecast_snapshot_lines`
-- (see docs/finance-forecast-snapshots-xano.md). Immutable INSERT-only app path.
--
-- NOTE: `revenue_forecast_lines` already exists (0001_ported_tables + 0014 natural key).
-- No further DDL required for forecast targets.

CREATE TABLE IF NOT EXISTS finance_forecast_snapshots (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  snapshot_label text NOT NULL,
  snapshot_type text NOT NULL,
  financial_year integer NOT NULL,
  scenario text NOT NULL,
  taken_at timestamptz NOT NULL,
  taken_by text,
  notes text,
  source_version_summary text,
  filter_context_json text
);

CREATE INDEX IF NOT EXISTS idx_finance_forecast_snapshots_fy_scenario_taken
  ON finance_forecast_snapshots (financial_year, scenario, taken_at DESC);

CREATE TABLE IF NOT EXISTS finance_forecast_snapshot_lines (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  snapshot_id bigint NOT NULL REFERENCES finance_forecast_snapshots (id) ON DELETE CASCADE,
  client_id text NOT NULL,
  client_name text NOT NULL,
  campaign_id text,
  mba_number text,
  media_plan_version_id text,
  version_number bigint,
  group_key text NOT NULL,
  line_key text NOT NULL,
  month_key text NOT NULL,
  amount numeric NOT NULL,
  fy_total numeric NOT NULL,
  source_hash text,
  source_debug_json text
);

CREATE INDEX IF NOT EXISTS idx_ffsl_snapshot_client_line_month
  ON finance_forecast_snapshot_lines (snapshot_id, client_id, line_key, month_key);

CREATE INDEX IF NOT EXISTS idx_ffsl_snapshot_group_line_month
  ON finance_forecast_snapshot_lines (snapshot_id, group_key, line_key, month_key);

CREATE INDEX IF NOT EXISTS idx_ffsl_snapshot_month
  ON finance_forecast_snapshot_lines (snapshot_id, month_key);

-- Ava read policies (idempotent; role may not exist in all envs)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ava_readonly') THEN
    EXECUTE 'ALTER TABLE finance_forecast_snapshots ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS ava_read ON finance_forecast_snapshots';
    EXECUTE 'CREATE POLICY ava_read ON finance_forecast_snapshots FOR SELECT TO ava_readonly USING (true)';
    EXECUTE 'ALTER TABLE finance_forecast_snapshot_lines ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS ava_read ON finance_forecast_snapshot_lines';
    EXECUTE 'CREATE POLICY ava_read ON finance_forecast_snapshot_lines FOR SELECT TO ava_readonly USING (true)';
    EXECUTE 'GRANT SELECT ON finance_forecast_snapshots TO ava_readonly';
    EXECUTE 'GRANT SELECT ON finance_forecast_snapshot_lines TO ava_readonly';
  END IF;
END $$;
