-- Migration 0028: MyHours mirrored time + structure links
-- Apply via Supabase SQL Editor / MCP after review — AUTHOR ONLY (Luke).
-- Do NOT drizzle-kit migrate from Cursor. Idempotent.
--
-- time_entries: read mirror of MyHours logs (AV never writes entries to MyHours).
-- myhours_links: AV client/campaign ↔ MyHours project/task ids.
-- myhours_sync_runs: per-cron audit row.

CREATE TABLE IF NOT EXISTS public.time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  myhours_log_id text NOT NULL,
  member_email text NOT NULL CHECK (member_email = lower(member_email)),
  entry_date date NOT NULL,
  duration_minutes integer NOT NULL,
  note text,
  myhours_project_id text,
  myhours_project_name text,
  myhours_task_id text,
  myhours_task_name text,
  client_id bigint,
  mba_number text CHECK (mba_number IS NULL OR mba_number = lower(mba_number)),
  mapping_source text NOT NULL DEFAULT 'unmapped'
    CHECK (mapping_source IN ('name_match', 'manual', 'unmapped')),
  raw jsonb,
  synced_at timestamptz NOT NULL,
  CONSTRAINT time_entries_myhours_log_id_unique UNIQUE (myhours_log_id)
);

CREATE INDEX IF NOT EXISTS idx_time_entries_member_email_entry_date
  ON public.time_entries (member_email, entry_date);
CREATE INDEX IF NOT EXISTS idx_time_entries_mba_number
  ON public.time_entries (mba_number);
CREATE INDEX IF NOT EXISTS idx_time_entries_client_id
  ON public.time_entries (client_id);

CREATE TABLE IF NOT EXISTS public.myhours_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('client_project', 'campaign_task')),
  client_id bigint,
  mba_number text CHECK (mba_number IS NULL OR mba_number = lower(mba_number)),
  myhours_id text NOT NULL,
  myhours_name text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT myhours_links_kind_myhours_id_unique UNIQUE (kind, myhours_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_myhours_links_kind_mba_unique
  ON public.myhours_links (kind, mba_number)
  WHERE mba_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.myhours_sync_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  entries_upserted integer NOT NULL DEFAULT 0,
  structures_created integer NOT NULL DEFAULT 0,
  unmapped_count integer NOT NULL DEFAULT 0,
  error text
);

ALTER TABLE public.time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.myhours_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.myhours_sync_runs ENABLE ROW LEVEL SECURITY;
