-- Migration 0032: AVA time-entry proposals (CX2-6)
-- Apply via Supabase SQL Editor — AUTHOR ONLY (Luke). Idempotent.

CREATE TABLE IF NOT EXISTS public.ava_time_entry_proposals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_note_id bigint NOT NULL
    REFERENCES public.client_notes(id) ON DELETE CASCADE,
  member_email text NOT NULL CHECK (member_email = lower(member_email)),
  entry_date date NOT NULL,
  duration_minutes integer NOT NULL,
  note text NOT NULL,
  client_id bigint,
  mba_number text CHECK (mba_number IS NULL OR mba_number = lower(mba_number)),
  myhours_project_id text,
  myhours_task_id text,
  status text NOT NULL DEFAULT 'proposed'
    CHECK (status IN (
      'proposed', 'confirmed', 'skipped',
      'blocked_overlap', 'blocked_structure'
    )),
  block_reason text,
  myhours_log_id text,
  confirmed_by_email text,
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ava_time_entry_proposals_note_member_unique
    UNIQUE (source_note_id, member_email),
  CONSTRAINT ava_time_entry_proposals_log_id_unique
    UNIQUE (myhours_log_id)
);

CREATE INDEX IF NOT EXISTS idx_ava_time_entry_proposals_week
  ON public.ava_time_entry_proposals (entry_date, status);
CREATE INDEX IF NOT EXISTS idx_ava_time_entry_proposals_member
  ON public.ava_time_entry_proposals (member_email, entry_date);

ALTER TABLE public.ava_time_entry_proposals ENABLE ROW LEVEL SECURITY;
-- No ava_readonly grants (commercially adjacent to hours).
