-- Migration 0090: finance_clearance_sends — last clearance email per month
-- AUTHOR ONLY. Apply via Supabase SQL Editor. Do not drizzle-kit migrate.
-- Idempotent: CREATE TABLE IF NOT EXISTS + migration_markers guard.
--
-- Do not SELECT this table against live Postgres until this file is applied (C-76).
-- Mirror: db/schema/financeClearanceSends.ts.
-- Nightly clearance and Clear for issue insert a row only after the email succeeds.

CREATE TABLE IF NOT EXISTS public.migration_markers (
    key         text primary key,
    applied_at  timestamptz not null default now(),
    note        text
);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.migration_markers WHERE key = '0090_finance_clearance_sends') THEN
    RAISE NOTICE '0090 already applied — no-op';
    RETURN;
  END IF;

  CREATE TABLE IF NOT EXISTS public.finance_clearance_sends (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month     text NOT NULL,
    sent_at   timestamptz NOT NULL DEFAULT now(),
    hash      text NOT NULL,
    counts    jsonb NOT NULL
  );

  CREATE INDEX IF NOT EXISTS finance_clearance_sends_month_sent_idx
    ON public.finance_clearance_sends (month, sent_at DESC);

  COMMENT ON TABLE public.finance_clearance_sends IS
    'Clearance emails. hash is sha256 of the sorted (invoice_id, state, amount) list. counts is {cleared, differs, missing}.';

  ALTER TABLE public.finance_clearance_sends ENABLE ROW LEVEL SECURITY;

  INSERT INTO public.migration_markers (key, note)
  VALUES (
    '0090_finance_clearance_sends',
    'finance_clearance_sends month, sent_at, hash, counts for clearance emails.'
  )
  ON CONFLICT (key) DO NOTHING;
END
$$;
