/**
 * Per-channel container descriptors (§4).
 *
 * Containers still render as today, but READ defaults / hydration / API field
 * lists from these descriptors instead of inline literals.
 *
 * Generated from scripts/tmp-container-fieldset-diffs.json — re-run
 * `node scripts/generate-container-channel-config.mjs` after regenerating diffs.
 *
 * Helpers:
 * - buildDefaultLineItem — only fields with inDefaults
 * - mapHydrationToForm — only inHydration; uses || "" / || false (NOT fieldMap.default)
 * - mapFormToApi — only inApi; uses || "" / || false
 */

import type { z } from "zod"
import {
  getPublishersForBvod,
  getPublishersForCinema,
  getPublishersForDigiAudio,
  getPublishersForDigiDisplay,
  getPublishersForDigiVideo,
  getPublishersForInfluencers,
  getPublishersForIntegration,
  getPublishersForMagazines,
  getPublishersForNewspapers,
  getPublishersForOoh,
  getPublishersForProgAudio,
  getPublishersForProgBvod,
  getPublishersForProgDisplay,
  getPublishersForProgOoh,
  getPublishersForProgVideo,
  getPublishersForRadio,
  getPublishersForSearch,
  getPublishersForSocialMedia,
  getPublishersForTelevision,
} from "@/lib/api"
import {
  BVOD_EXPERT_CHANNEL_CONFIG,
  CINEMA_EXPERT_CHANNEL_CONFIG,
  DIGIAUDIO_EXPERT_CHANNEL_CONFIG,
  DIGITALDISPLAY_EXPERT_CHANNEL_CONFIG,
  DIGIVIDEO_EXPERT_CHANNEL_CONFIG,
  INFLUENCERS_EXPERT_CHANNEL_CONFIG,
  INTEGRATION_EXPERT_CHANNEL_CONFIG,
  MAGAZINES_EXPERT_CHANNEL_CONFIG,
  NEWSPAPER_EXPERT_CHANNEL_CONFIG,
  OOH_EXPERT_CHANNEL_CONFIG,
  PRODUCTION_EXPERT_CHANNEL_CONFIG,
  PROGAUDIO_EXPERT_CHANNEL_CONFIG,
  PROGBVOD_EXPERT_CHANNEL_CONFIG,
  PROGDISPLAY_EXPERT_CHANNEL_CONFIG,
  PROGOOH_EXPERT_CHANNEL_CONFIG,
  PROGVIDEO_EXPERT_CHANNEL_CONFIG,
  RADIO_EXPERT_CHANNEL_CONFIG,
  SEARCH_EXPERT_CHANNEL_CONFIG,
  SOCIALMEDIA_EXPERT_CHANNEL_CONFIG,
  TELEVISION_EXPERT_CHANNEL_CONFIG,
  createEmptyProgAudioExpertRow,
  createEmptyProgBvodExpertRow,
  createEmptyProgDisplayExpertRow,
  createEmptyProgOohExpertRow,
  createEmptyProgVideoExpertRow,
  createEmptySearchExpertRow,
  type ExpertGridChannelConfig,
} from "@/lib/mediaplan/expertGridChannelConfig"
import {
  mapProgAudioExpertRowsToStandardLineItems,
  mapProgBvodExpertRowsToStandardLineItems,
  mapProgDisplayExpertRowsToStandardLineItems,
  mapProgOohExpertRowsToStandardLineItems,
  mapProgVideoExpertRowsToStandardLineItems,
  mapSearchExpertRowsToStandardLineItems,
  mapStandardBvodLineItemsToExpertRows,
  mapStandardCinemaLineItemsToExpertRows,
  mapStandardDigiAudioLineItemsToExpertRows,
  mapStandardDigiDisplayLineItemsToExpertRows,
  mapStandardDigiVideoLineItemsToExpertRows,
  mapStandardInfluencersLineItemsToExpertRows,
  mapStandardIntegrationLineItemsToExpertRows,
  mapStandardMagazineLineItemsToExpertRows,
  mapStandardNewspaperLineItemsToExpertRows,
  mapStandardOohLineItemsToExpertRows,
  mapStandardProductionLineItemsToExpertRows,
  mapStandardProgAudioLineItemsToExpertRows,
  mapStandardProgBvodLineItemsToExpertRows,
  mapStandardProgDisplayLineItemsToExpertRows,
  mapStandardProgOohLineItemsToExpertRows,
  mapStandardProgVideoLineItemsToExpertRows,
  mapStandardRadioLineItemsToExpertRows,
  mapStandardSearchLineItemsToExpertRows,
  mapStandardSocialMediaLineItemsToExpertRows,
  mapStandardTvLineItemsToExpertRows,
} from "@/lib/mediaplan/expertChannelMappings"
import {
  mergeProgAudioStandardFromExpertWithPrevious,
  mergeProgBvodStandardFromExpertWithPrevious,
  mergeProgDisplayStandardFromExpertWithPrevious,
  mergeProgOohStandardFromExpertWithPrevious,
  mergeProgVideoStandardFromExpertWithPrevious,
  mergeSearchStandardFromExpertWithPrevious,
  serializeProgAudioExpertRowsBaseline,
  serializeProgAudioStandardLineItemsBaseline,
  serializeProgBvodExpertRowsBaseline,
  serializeProgBvodStandardLineItemsBaseline,
  serializeProgDisplayExpertRowsBaseline,
  serializeProgDisplayStandardLineItemsBaseline,
  serializeProgOohExpertRowsBaseline,
  serializeProgOohStandardLineItemsBaseline,
  serializeProgVideoExpertRowsBaseline,
  serializeProgVideoStandardLineItemsBaseline,
  serializeSearchExpertRowsBaseline,
  serializeSearchStandardLineItemsBaseline,
} from "@/lib/mediaplan/expertModeSwitch"
import type { MediaTypeThemeKey } from "@/lib/mediaplan/mediaTypeAccents"
import { MEDIA_TYPE_ID_CODES } from "@/lib/mediaplan/lineItemIds"
import {
  bvodFormSchema,
  cinemaFormSchema,
  digiAudioFormSchema,
  digidisplayFormSchema,
  digivideoFormSchema,
  influencersFormSchema,
  integrationFormSchema,
  magazinesFormSchema,
  newspapersFormSchema,
  oohFormSchema,
  productionFormSchema,
  progAudioFormSchema,
  progBvodFormSchema,
  progDisplayFormSchema,
  progOOHFormSchema,
  progVideoFormSchema,
  radioFormSchema,
  searchFormSchema,
  socialMediaFormSchema,
  televisionFormSchema,
} from "@/lib/mediaplan/schemas"

export type FieldMapEntry = {
  camel: string
  snake: string
  excel: string | null
  /** Form default when inDefaults; null = hydration/API-only (no form default). */
  default: string | boolean | number | null
  inDefaults: boolean
  inHydration: boolean
  inApi: boolean
}

type CalculatedVariant =
  | "cpcCpvCpm"
  | "radio"
  | "ooh"
  | "cinema"
  | "newspaper"
  | "magazine"

/** Local publisher shape — matches container-local Publisher interfaces. */
type ContainerPublisher = {
  id: number
  publisher_name: string
}

/** UI chrome for MediaChannelContainer (titles, theme, timeline key, exit attr). */
type ContainerChannelShell = {
  title: string
  themeKey: MediaTypeThemeKey
  timelineMediaTypeKey: string
  loadLabel: string
  /** data-* attribute on the exit-confirm "Yes" button */
  exitConfirmYesAttr: string
  entryModeAriaLabel?: string
  expertDialogTitle?: string
}

export type ContainerChannelConfig = {
  mediaTypeString: string
  mediaTypeIdCode: string
  schema: z.ZodTypeAny
  fetchPublishers: (() => Promise<ContainerPublisher[]>) | null
  toExpert: (...args: any[]) => any
  fromExpert: ((...args: any[]) => any) | null
  mergeFromExpert: ((...args: any[]) => any) | null
  serializeStandardBaseline: ((...args: any[]) => string) | null
  serializeExpertBaseline: ((...args: any[]) => string) | null
  createEmptyExpertRow: ((...args: any[]) => any) | null
  billingMediaTypeLabel: string
  expertFromFeeKey: string | null
  summaryDimensions: Record<string, string>
  deliverableRoundingPolicy: "raw" | "rounded"
  gridConfig: ExpertGridChannelConfig<any>
  calculatedVariant: CalculatedVariant
  hasBursts: boolean
  fieldMap: FieldMapEntry[]
  /** Required for MediaChannelContainer; optional until a channel is converted. */
  shell?: ContainerChannelShell
}

/**
 * Build a fresh line-item defaults object from fieldMap (inDefaults only).
 * Returns `any` so RHF `append` / `defaultValues` accept the spread without
 * narrowing away required schema keys.
 */
export function buildDefaultLineItem(fieldMap: FieldMapEntry[]): any {
  const out: Record<string, any> = {}
  for (const entry of fieldMap) {
    if (!entry.inDefaults) continue
    out[entry.camel] = entry.default
  }
  return out
}

/**
 * Map an API/persisted line item → form camelCase fields (inHydration only).
 * Mirrors current transforms: string fields || "", booleans || false.
 * Does NOT fall back to fieldMap.default (preserves Television buy_type → "").
 */
export function mapHydrationToForm(
  fieldMap: FieldMapEntry[],
  apiItem: Record<string, unknown> | null | undefined,
): any {
  const src = apiItem ?? {}
  const out: Record<string, any> = {}
  for (const entry of fieldMap) {
    if (!entry.inHydration) continue
    const raw = src[entry.snake] ?? src[entry.camel]
    if (typeof entry.default === "boolean") {
      out[entry.camel] = Boolean(raw) || false
    } else {
      out[entry.camel] = (raw as string | undefined) || ""
    }
  }
  return out
}

/**
 * Map a form line item → API snake_case fields (inApi only).
 * Mirrors current transforms: string fields || "", booleans || false.
 */
export function mapFormToApi(
  fieldMap: FieldMapEntry[],
  formItem: Record<string, unknown> | null | undefined,
): any {
  const src = formItem ?? {}
  const out: Record<string, any> = {}
  for (const entry of fieldMap) {
    if (!entry.inApi) continue
    const raw = src[entry.camel]
    if (typeof entry.default === "boolean") {
      out[entry.snake] = Boolean(raw) || false
    } else {
      out[entry.snake] = (raw as string | undefined) || ""
    }
  }
  return out
}


export const PROGDISPLAY_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Programmatic Display",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.progDisplay,
  schema: progDisplayFormSchema,
  fetchPublishers: getPublishersForProgDisplay,
  toExpert: mapStandardProgDisplayLineItemsToExpertRows,
  fromExpert: mapProgDisplayExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeProgDisplayStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeProgDisplayStandardLineItemsBaseline,
  serializeExpertBaseline: serializeProgDisplayExpertRowsBaseline,
  createEmptyExpertRow: createEmptyProgDisplayExpertRow as any,
  billingMediaTypeLabel: "prog display",
  expertFromFeeKey: "feePctProgDisplay",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Prog Display Media",
    themeKey: "progdisplay",
    timelineMediaTypeKey: "progDisplay",
    loadLabel: "Programmatic Display",
    exitConfirmYesAttr: "data-progdisplayexpert-exit-yes",
    entryModeAriaLabel: "Prog Display Media entry mode",
    expertDialogTitle: "Prog Display Media Expert Mode",
  },

  gridConfig: PROGDISPLAY_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const PROGVIDEO_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Programmatic Video",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.progVideo,
  schema: progVideoFormSchema,
  fetchPublishers: getPublishersForProgVideo,
  toExpert: mapStandardProgVideoLineItemsToExpertRows,
  fromExpert: mapProgVideoExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeProgVideoStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeProgVideoStandardLineItemsBaseline,
  serializeExpertBaseline: serializeProgVideoExpertRowsBaseline,
  createEmptyExpertRow: createEmptyProgVideoExpertRow as any,
  billingMediaTypeLabel: "Prog Video",
  expertFromFeeKey: "feePctProgVideo",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Prog Video Media",
    themeKey: "progvideo",
    timelineMediaTypeKey: "progVideo",
    loadLabel: "Programmatic Video",
    exitConfirmYesAttr: "data-progvideoexpert-exit-yes",
    entryModeAriaLabel: "Prog Video Media entry mode",
    expertDialogTitle: "Prog Video Media Expert Mode",
  },
  gridConfig: PROGVIDEO_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const PROGBVOD_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Programmatic BVOD",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.progBVOD,
  schema: progBvodFormSchema,
  fetchPublishers: getPublishersForProgBvod,
  toExpert: mapStandardProgBvodLineItemsToExpertRows,
  fromExpert: mapProgBvodExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeProgBvodStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeProgBvodStandardLineItemsBaseline,
  serializeExpertBaseline: serializeProgBvodExpertRowsBaseline,
  createEmptyExpertRow: createEmptyProgBvodExpertRow as any,
  billingMediaTypeLabel: "prog bvod",
  expertFromFeeKey: "feePctProgBvod",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Prog BVOD Media",
    themeKey: "progbvod",
    timelineMediaTypeKey: "progBvod",
    loadLabel: "Programmatic BVOD",
    exitConfirmYesAttr: "data-progbvodexpert-exit-yes",
    entryModeAriaLabel: "Prog BVOD Media entry mode",
    expertDialogTitle: "Prog BVOD Media Expert Mode",
  },
  gridConfig: PROGBVOD_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const PROGAUDIO_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Programmatic Audio",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.progAudio,
  schema: progAudioFormSchema,
  fetchPublishers: getPublishersForProgAudio,
  toExpert: mapStandardProgAudioLineItemsToExpertRows,
  fromExpert: mapProgAudioExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeProgAudioStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeProgAudioStandardLineItemsBaseline,
  serializeExpertBaseline: serializeProgAudioExpertRowsBaseline,
  createEmptyExpertRow: createEmptyProgAudioExpertRow as any,
  billingMediaTypeLabel: "progaudio",
  expertFromFeeKey: "feePctProgAudio",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Prog Audio Media",
    themeKey: "progaudio",
    timelineMediaTypeKey: "progAudio",
    loadLabel: "Programmatic Audio",
    exitConfirmYesAttr: "data-progaudioexpert-exit-yes",
    entryModeAriaLabel: "Prog Audio Media entry mode",
    expertDialogTitle: "Prog Audio Media Expert Mode",
  },
  gridConfig: PROGAUDIO_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const PROGOOH_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Programmatic OOH",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.progOOH,
  schema: progOOHFormSchema,
  fetchPublishers: getPublishersForProgOoh,
  toExpert: mapStandardProgOohLineItemsToExpertRows,
  fromExpert: mapProgOohExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeProgOohStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeProgOohStandardLineItemsBaseline,
  serializeExpertBaseline: serializeProgOohExpertRowsBaseline,
  createEmptyExpertRow: createEmptyProgOohExpertRow as any,
  billingMediaTypeLabel: "prog ooh",
  expertFromFeeKey: "feePctProgOoh",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Prog OOH Media",
    themeKey: "progooh",
    timelineMediaTypeKey: "progOoh",
    loadLabel: "Programmatic OOH",
    exitConfirmYesAttr: "data-progoohexpert-exit-yes",
    entryModeAriaLabel: "Prog OOH Media entry mode",
    expertDialogTitle: "Prog OOH Media Expert Mode",
  },
  gridConfig: PROGOOH_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const DIGITALDISPLAY_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Digital Display",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.digitalDisplay,
  schema: digidisplayFormSchema,
  fetchPublishers: getPublishersForDigiDisplay,
  toExpert: mapStandardDigiDisplayLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "digital display",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: DIGITALDISPLAY_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: false,
    },
  ],
}

export const DIGITALVIDEO_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Digital Video",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.digitalVideo,
  schema: digivideoFormSchema,
  fetchPublishers: getPublishersForDigiVideo,
  toExpert: mapStandardDigiVideoLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "digital video",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: DIGIVIDEO_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const DIGITALAUDIO_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Digital Audio",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.digitalAudio,
  schema: digiAudioFormSchema,
  fetchPublishers: getPublishersForDigiAudio,
  toExpert: mapStandardDigiAudioLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "digital audio",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "rounded" as const,
  gridConfig: DIGIAUDIO_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const BVOD_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "BVOD",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.bvod,
  schema: bvodFormSchema,
  fetchPublishers: getPublishersForBvod,
  toExpert: mapStandardBvodLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "bvod",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "rounded" as const,
  gridConfig: BVOD_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "site",
      snake: "site",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const TELEVISION_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Television",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.television,
  schema: televisionFormSchema,
  fetchPublishers: getPublishersForTelevision,
  toExpert: mapStandardTvLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "television",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "rounded" as const,
  gridConfig: TELEVISION_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "CPP",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "daypart",
      snake: "daypart",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "station",
      snake: "station",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "tarps",
      snake: "tarps",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: false,
    },
  ],
}

export const RADIO_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Radio",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.radio,
  schema: radioFormSchema,
  fetchPublishers: getPublishersForRadio,
  toExpert: mapStandardRadioLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "radio",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: RADIO_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "radio",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: false,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: false,
      inApi: true,
    },
    {
      camel: "duration",
      snake: "duration",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "format",
      snake: "format",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "station",
      snake: "station",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const SEARCH_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Search",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.search,
  schema: searchFormSchema,
  fetchPublishers: getPublishersForSearch,
  toExpert: mapStandardSearchLineItemsToExpertRows,
  fromExpert: mapSearchExpertRowsToStandardLineItems as any,
  mergeFromExpert: mergeSearchStandardFromExpertWithPrevious as any,
  serializeStandardBaseline: serializeSearchStandardLineItemsBaseline,
  serializeExpertBaseline: serializeSearchExpertRowsBaseline,
  createEmptyExpertRow: createEmptySearchExpertRow as any,
  billingMediaTypeLabel: "search",
  expertFromFeeKey: "feePctSearch",
  summaryDimensions: {
    Platform: "platform",
    "Bid Strategy": "bidStrategy",
    "Buy Type": "buyType",
  },
  deliverableRoundingPolicy: "raw" as const,
  shell: {
    title: "Search Media",
    themeKey: "search",
    timelineMediaTypeKey: "search",
    loadLabel: "Search",
    exitConfirmYesAttr: "data-searchexpert-exit-yes",
    entryModeAriaLabel: "Search Media entry mode",
    expertDialogTitle: "Search Media Expert Mode",
  },
  gridConfig: SEARCH_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const SOCIALMEDIA_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Social Media",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.socialMedia,
  schema: socialMediaFormSchema,
  fetchPublishers: getPublishersForSocialMedia,
  toExpert: mapStandardSocialMediaLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "social media",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: SOCIALMEDIA_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const INFLUENCERS_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Influencers",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.influencers,
  schema: influencersFormSchema,
  fetchPublishers: getPublishersForInfluencers,
  toExpert: mapStandardInfluencersLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "influencers",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: INFLUENCERS_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "campaign",
      snake: "campaign",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "objective",
      snake: "objective",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const INTEGRATION_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Integration",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.integration,
  schema: integrationFormSchema,
  fetchPublishers: getPublishersForIntegration,
  toExpert: mapStandardIntegrationLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "integration",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: INTEGRATION_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "campaign",
      snake: "campaign",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creative",
      snake: "creative",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "creativeTargeting",
      snake: "creative_targeting",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noAdserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "objective",
      snake: "objective",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "platform",
      snake: "platform",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "targetingAttribute",
      snake: "targeting_attribute",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const OOH_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "OOH",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.ooh,
  schema: oohFormSchema,
  fetchPublishers: getPublishersForOoh,
  toExpert: mapStandardOohLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "ooh",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "rounded" as const,
  gridConfig: OOH_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "ooh",
  hasBursts: true,
  fieldMap: [
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "format",
      snake: "format",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noAdserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "type",
      snake: "type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const CINEMA_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Cinema",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.cinema,
  schema: cinemaFormSchema,
  fetchPublishers: getPublishersForCinema,
  toExpert: mapStandardCinemaLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "cinema",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "rounded" as const,
  gridConfig: CINEMA_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cinema",
  hasBursts: true,
  fieldMap: [
    {
      camel: "bidStrategy",
      snake: "bid_strategy",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "duration",
      snake: "duration",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "format",
      snake: "format",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "station",
      snake: "station",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const NEWSPAPER_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Newspaper",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.newspaper,
  schema: newspapersFormSchema,
  fetchPublishers: getPublishersForNewspapers,
  toExpert: mapStandardNewspaperLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "newspaper",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: NEWSPAPER_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "newspaper",
  hasBursts: true,
  fieldMap: [
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "format",
      snake: "format",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "title",
      snake: "title",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const MAGAZINES_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Magazines",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.magazines,
  schema: magazinesFormSchema,
  fetchPublishers: getPublishersForMagazines,
  toExpert: mapStandardMagazineLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "magazines",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: MAGAZINES_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "magazine",
  hasBursts: true,
  fieldMap: [
    {
      camel: "budgetIncludesFees",
      snake: "budget_includes_fees",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyType",
      snake: "buy_type",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "buyingDemo",
      snake: "buying_demo",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "clientPaysForMedia",
      snake: "client_pays_for_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "fixedCostMedia",
      snake: "fixed_cost_media",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "format",
      snake: "format",
      excel: null,
      default: null,
      inDefaults: false,
      inHydration: false,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "network",
      snake: "network",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "noadserving",
      snake: "no_adserving",
      excel: null,
      default: false,
      inDefaults: true,
      inHydration: true,
      inApi: false,
    },
    {
      camel: "placement",
      snake: "placement",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "size",
      snake: "size",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "title",
      snake: "title",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}

export const PRODUCTION_CONTAINER_CONFIG: ContainerChannelConfig = {
  mediaTypeString: "Production",
  mediaTypeIdCode: MEDIA_TYPE_ID_CODES.production,
  schema: productionFormSchema,
  fetchPublishers: null,
  toExpert: mapStandardProductionLineItemsToExpertRows,
    fromExpert: null,
  mergeFromExpert: null,
  serializeStandardBaseline: null,
  serializeExpertBaseline: null,
  createEmptyExpertRow: null,
  billingMediaTypeLabel: "production",
  expertFromFeeKey: null,
  summaryDimensions: {},
  deliverableRoundingPolicy: "raw" as const,
  gridConfig: PRODUCTION_EXPERT_CHANNEL_CONFIG,
  calculatedVariant: "cpcCpvCpm",
  hasBursts: false,
  fieldMap: [
    {
      camel: "description",
      snake: "description",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "market",
      snake: "market",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "mediaType",
      snake: "media_type",
      excel: null,
      default: "mediaTypeOptions[0]?.value || \"",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "publisher",
      snake: "publisher",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
    {
      camel: "unitRate",
      snake: "unit_rate",
      excel: null,
      default: "",
      inDefaults: true,
      inHydration: true,
      inApi: true,
    },
  ],
}
