-- ASSEMBLEDVIEW.MART.SP_REFRESH_GOOGLESEARCHPACING_ROLLING
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

CREATE OR REPLACE PROCEDURE "SP_REFRESH_GOOGLESEARCHPACING_ROLLING"("DAYS_BACK" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
begin
  merge into ASSEMBLEDVIEW.MART.SEARCH_PACING_FACT t
  using (
    select
      CHANNEL,
      DATE_DAY,
      LINE_ITEM_ID,
      LINE_ITEM_NAME,
      PLATFORM_LINE_ITEM_ID,
      CAMPAIGN_ID,
      CAMPAIGN_NAME,
      CUSTOMER_ID,
      AMOUNT_SPENT,
      IMPRESSIONS,
      CLICKS,
      CONVERSIONS,
      REVENUE,
      TOP_IMPRESSION_PERCENTAGE,
      ABSOLUTE_TOP_IMPRESSION_PERCENTAGE,
      MAX_FIVETRAN_SYNCED_AT,
      current_timestamp() as UPDATED_AT
    from ASSEMBLEDVIEW.MART.VW_PACING_GOOGLE_SEARCH_DAILY
    where DATE_DAY >= dateadd(day, -:DAYS_BACK, current_date())
  ) s
  on  t.CHANNEL = s.CHANNEL
  and t.DATE_DAY = s.DATE_DAY
  and lower(trim(t.PLATFORM_LINE_ITEM_ID)) = lower(trim(s.PLATFORM_LINE_ITEM_ID))
  when matched then update set
    LINE_ITEM_ID = s.LINE_ITEM_ID,
    LINE_ITEM_NAME = s.LINE_ITEM_NAME,
    CAMPAIGN_ID = s.CAMPAIGN_ID,
    CAMPAIGN_NAME = s.CAMPAIGN_NAME,
    CUSTOMER_ID = s.CUSTOMER_ID,
    AMOUNT_SPENT = s.AMOUNT_SPENT,
    IMPRESSIONS = s.IMPRESSIONS,
    CLICKS = s.CLICKS,
    CONVERSIONS = s.CONVERSIONS,
    REVENUE = s.REVENUE,
    TOP_IMPRESSION_PERCENTAGE = s.TOP_IMPRESSION_PERCENTAGE,
    ABSOLUTE_TOP_IMPRESSION_PERCENTAGE = s.ABSOLUTE_TOP_IMPRESSION_PERCENTAGE,
    MAX_FIVETRAN_SYNCED_AT = s.MAX_FIVETRAN_SYNCED_AT,
    UPDATED_AT = current_timestamp()
  when not matched then insert (
    CHANNEL, DATE_DAY,
    LINE_ITEM_ID, LINE_ITEM_NAME, PLATFORM_LINE_ITEM_ID,
    CAMPAIGN_ID, CAMPAIGN_NAME, CUSTOMER_ID,
    AMOUNT_SPENT, IMPRESSIONS, CLICKS, CONVERSIONS, REVENUE,
    TOP_IMPRESSION_PERCENTAGE, ABSOLUTE_TOP_IMPRESSION_PERCENTAGE,
    MAX_FIVETRAN_SYNCED_AT, UPDATED_AT
  ) values (
    s.CHANNEL, s.DATE_DAY,
    s.LINE_ITEM_ID, s.LINE_ITEM_NAME, s.PLATFORM_LINE_ITEM_ID,
    s.CAMPAIGN_ID, s.CAMPAIGN_NAME, s.CUSTOMER_ID,
    s.AMOUNT_SPENT, s.IMPRESSIONS, s.CLICKS, s.CONVERSIONS, s.REVENUE,
    s.TOP_IMPRESSION_PERCENTAGE, s.ABSOLUTE_TOP_IMPRESSION_PERCENTAGE,
    s.MAX_FIVETRAN_SYNCED_AT, current_timestamp()
  );
  return ''OK'';
end;
';
