-- DDL for methodology panel + engine params (R2).
-- Tables were not visible to AV_APP_WRITE_ROLE at build time; CREATE IF NOT EXISTS
-- is safe if Luke already created them under another role.
-- Methodology content (8 rows) is expected to be seeded separately by Luke;
-- this file only ensures the shape the app queries.

USE SCHEMA ASSEMBLEDVIEW.MART;

CREATE TABLE IF NOT EXISTS PLANNING_METHODOLOGY (
  METHODOLOGY_ID VARCHAR(64) NOT NULL,
  TITLE VARCHAR(256) NOT NULL,
  FORMULA_TEXT VARCHAR(16777216),
  DESCRIPTION VARCHAR(16777216),
  DATA_SOURCE VARCHAR(256),
  SORT_ORDER NUMBER(10, 0) NOT NULL DEFAULT 0,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (METHODOLOGY_ID)
);

CREATE TABLE IF NOT EXISTS PLANNING_ENGINE_PARAMS (
  PARAM_KEY VARCHAR(64) NOT NULL,
  PARAM_VALUE FLOAT NOT NULL,
  DESCRIPTION VARCHAR(16777216),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (PARAM_KEY)
);

-- Grant read to the app role if you create as ACCOUNTADMIN:
-- GRANT SELECT ON TABLE PLANNING_METHODOLOGY TO ROLE AV_APP_WRITE_ROLE;
-- GRANT SELECT ON TABLE PLANNING_ENGINE_PARAMS TO ROLE AV_APP_WRITE_ROLE;
