-- Re-runnable safety net: consumer read role for pacing views.
-- Run with a role that holds GRANT OPTION on these objects (or OWNERSHIP).
-- Prerequisite: AV_APP_READ_ROLE must already have USAGE on database ASSEMBLEDVIEW
-- and schemas VW_PACING (and any parents), as typically created in 00_schemas.sql.

GRANT SELECT ON VIEW ASSEMBLEDVIEW.VW_PACING.V_LINE_ITEM_PACING TO ROLE AV_APP_READ_ROLE;
GRANT SELECT ON VIEW ASSEMBLEDVIEW.VW_PACING.V_LINE_ITEM_PACING_DAILY TO ROLE AV_APP_READ_ROLE;
GRANT SELECT ON VIEW ASSEMBLEDVIEW.VW_PACING.V_DELIVERY_PACING TO ROLE AV_APP_READ_ROLE;
GRANT SELECT ON VIEW ASSEMBLEDVIEW.VW_PACING.V_PACING_ALERTS TO ROLE AV_APP_READ_ROLE;
