CREATE TYPE "public"."line_channel" AS ENUM('television', 'radio', 'cinema', 'newspaper', 'magazines', 'ooh', 'prog_display', 'prog_video', 'prog_audio', 'prog_bvod', 'prog_ooh', 'digi_display', 'digi_video', 'digi_audio', 'digi_bvod', 'social', 'search', 'influencers', 'integrations', 'production');--> statement-breakpoint
CREATE TYPE "public"."schedule_basis" AS ENUM('billing', 'delivery');--> statement-breakpoint
CREATE TYPE "public"."schedule_component" AS ENUM('media', 'fee');--> statement-breakpoint
CREATE TYPE "public"."schedule_source" AS ENUM('computed', 'override');--> statement-breakpoint
CREATE TABLE "audio_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audio_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "bvod_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bvod_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "campaign_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mp_client_name" text,
	"mba_number" text,
	"version_number" bigint,
	"campaign_name" text,
	"media_type" text,
	"publisher" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric,
	"line_item_id" text
);
--> statement-breakpoint
CREATE TABLE "client_domains" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_domains_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"email_domain" text
);
--> statement-breakpoint
CREATE TABLE "client_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mp_client_name" text,
	"publisher_name" text,
	"media_type" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric
);
--> statement-breakpoint
CREATE TABLE "client_notes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"mba_number" text,
	"source" text,
	"title" text,
	"body" text,
	"meeting_date" timestamp with time zone,
	"fireflies_meeting_id" text,
	"participants" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clientdashboard" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clientdashboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_dashboard" text,
	"idgoogleads_dashboard" text,
	"idmeta_dashboard" text,
	"idcm360_dashboard" text,
	"iddv360_dashboard" text,
	"idtiktok_dashboard" text,
	"idlinkedin_dashboard" text,
	"idpinterest_dashboard" text,
	"idquantcast_dashboard" text,
	"idtaboola_dashboard" text,
	"idsnapchat_dashboard" text,
	"idbing_dashboard" text,
	"idvistar_dashboard" text,
	"idga4_dashboard" text,
	"idmerchantcentre_dashboard" text,
	"idshopify_dashboard" text
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mp_client_name" text,
	"clientcategory" text,
	"abn" text,
	"mbaidentifier" text,
	"legalbusinessname" text,
	"streetaddress" text,
	"suburb" text,
	"state_dropdown" text,
	"postcode" text,
	"keyfirstname" text,
	"keylastname" text,
	"keyphone" bigint,
	"keyemail" text,
	"billingfirstname" text,
	"billinglastname" text,
	"billingphone" bigint,
	"billingemail" text,
	"monthlyretainer" numeric,
	"organicsocial" numeric,
	"television_checkbox" boolean,
	"radio_checkbox" boolean,
	"newspapers_checkbox" boolean,
	"magazines_checkbox" boolean,
	"ooh_checkbox" boolean,
	"cinema_checkbox" boolean,
	"digitaldisplay_checkbox" boolean,
	"digitalaudio_checkbox" boolean,
	"digitalvideo_checkbox" boolean,
	"bvod_checkbox" boolean,
	"feesocial" numeric,
	"feesearch" numeric,
	"feeprogdisplay" numeric,
	"feeprogvideo" numeric,
	"feeprogbvod" numeric,
	"feeprogaudio" numeric,
	"feeprogooh" numeric,
	"feecontentcreator" numeric,
	"adservvideo" numeric,
	"adservimp" numeric,
	"adservdisplay" numeric,
	"adservaudio" numeric,
	"idgoogleads" text,
	"idmeta" text,
	"idcm360" text,
	"iddv360" text,
	"idtiktok" text,
	"idlinkedin" text,
	"idpinterest" text,
	"idquantcast" text,
	"idtaboola" text,
	"idsnapchat" text,
	"idbing" text,
	"idvistar" text,
	"idga4" text,
	"idmerchantcentre" text,
	"idshopify" text,
	"payment_days" bigint,
	"payment_terms" text,
	"brand_colour" text,
	"client_logo" jsonb,
	"website" text,
	"facebook_url" text,
	"instagram_url" text,
	"linkedin_url" text,
	"tiktok_url" text,
	"client_brain" text,
	"client_brain_updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "creative_asset" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "creative_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mba_number" text,
	"media_plan_master_id" bigint,
	"line_item_id" text,
	"source_table" text,
	"asset_name" text,
	"original_filename" text,
	"mime_type" text,
	"file_size_bytes" bigint,
	"width_px" bigint,
	"height_px" bigint,
	"duration_seconds" numeric,
	"blob_url" text,
	"blob_pathname" text,
	"status" text,
	"uploaded_by_email" text,
	"uploaded_by_role" text
);
--> statement-breakpoint
CREATE TABLE "display_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "display_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "finance_billing_line_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_billing_line_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finance_billing_records_id" bigint,
	"item_code" text,
	"line_type" text,
	"media_type" text,
	"description" text,
	"publisher_name" text,
	"amount" numeric,
	"client_pays_media" boolean,
	"sort_order" bigint,
	"updated_at" timestamp with time zone,
	"line_item_id" text,
	"line_status" text,
	"received_at" timestamp with time zone,
	"received_amount" numeric,
	"note" text,
	"orphaned" boolean,
	"media_plan_version_number" bigint
);
--> statement-breakpoint
CREATE TABLE "finance_billing_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_billing_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"client_name" text,
	"billing_type" text,
	"mba_number" text,
	"campaign_name" text,
	"po_number" text,
	"billing_month" text,
	"invoice_date" date,
	"payment_days" bigint,
	"payment_terms" text,
	"status" text,
	"total" numeric,
	"has_pending_edits" boolean,
	"source_billing_schedule_id" bigint,
	"updated_at" timestamp with time zone,
	"billed" boolean,
	"billed_at" timestamp with time zone,
	"billed_by" bigint,
	"notes" text,
	"exported_at" timestamp with time zone,
	"exported_by" bigint,
	"invoice_key" text
);
--> statement-breakpoint
CREATE TABLE "finance_edits" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_edits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finance_billing_records_id" bigint,
	"finance_billing_line_items_id" bigint,
	"edit_type" text,
	"field_name" text,
	"old_value" text,
	"new_value" text,
	"edit_status" text,
	"edited_by" bigint,
	"edited_by_name" text,
	"published_at" timestamp with time zone,
	"record_type" text
);
--> statement-breakpoint
CREATE TABLE "finance_saved_views" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_saved_views_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" bigint,
	"view_name" text,
	"filters" jsonb,
	"is_default" boolean,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "magazines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "magazines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"title" text
);
--> statement-breakpoint
CREATE TABLE "magazines_adsizes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "magazines_adsizes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"adsize" text
);
--> statement-breakpoint
CREATE TABLE "media_container_best_practice" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_container_best_practice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"media_container" text,
	"best_practice" jsonb,
	"is_active" boolean,
	"_name" text
);
--> statement-breakpoint
CREATE TABLE "newspaper_adsizes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newspaper_adsizes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"adsize" text
);
--> statement-breakpoint
CREATE TABLE "newspapers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newspapers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"title" text
);
--> statement-breakpoint
CREATE TABLE "pacing_orphan_fixes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pacing_orphan_fixes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"admin_user_email" text,
	"channel" text,
	"platform_line_item_id" text,
	"previous_line_item_id" text,
	"new_line_item_id" text,
	"ad_group_name" text,
	"campaign_name" text,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "planning_audiences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planning_audiences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"mba_number" text,
	"name" text,
	"definition_json" jsonb,
	"composed_wc" numeric,
	"client_visible" boolean,
	"created_by_email" text
);
--> statement-breakpoint
CREATE TABLE "publisher_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "publisher_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"publisher" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric,
	"media_type" text
);
--> statement-breakpoint
CREATE TABLE "publishers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "publishers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"publisher_name" text,
	"publisherid" text,
	"publishertype" text,
	"billingagency" text,
	"financecode" text,
	"pub_television" boolean,
	"pub_radio" boolean,
	"pub_newspaper" boolean,
	"pub_magazines" boolean,
	"pub_ooh" boolean,
	"pub_cinema" boolean,
	"pub_digidisplay" boolean,
	"pub_digiaudio" boolean,
	"pub_digivideo" boolean,
	"pub_bvod" boolean,
	"pub_integration" boolean,
	"pub_search" boolean,
	"pub_socialmedia" boolean,
	"pub_progdisplay" boolean,
	"pub_progvideo" boolean,
	"pub_progbvod" boolean,
	"pub_progaudio" boolean,
	"pub_progooh" boolean,
	"pub_influencers" boolean,
	"radio_comms" numeric,
	"newspaper_comms" numeric,
	"television_comms" numeric,
	"magazines_comms" numeric,
	"ooh_comms" numeric,
	"cinema_comms" numeric,
	"digidisplay_comms" numeric,
	"digiaudio_comms" numeric,
	"digivideo_comms" numeric,
	"bvod_comms" numeric,
	"integration_comms" numeric,
	"search_comms" numeric,
	"progdisplay_comms" numeric,
	"progvideo_comms" numeric,
	"progbvod_comms" numeric,
	"progaudio_comms" numeric,
	"progooh_comms" numeric,
	"influencers_comms" numeric,
	"digitaldisplay_cpm_default" numeric,
	"digitaldisplay_cpc_default" numeric,
	"digitaldisplay_cpv_default" numeric,
	"digitaldisplay_ctr_default" numeric,
	"digitaldisplay_vtr_default" numeric,
	"digitaldisplay_frequency_default" numeric,
	"digitalvideo_cpm_default" numeric,
	"digitalvideo_cpc_default" numeric,
	"digitalvideo_cpv_default" numeric,
	"digitalvideo_ctr_default" numeric,
	"digitalvideo_vtr_default" numeric,
	"digitalvideo_frequency_default" numeric,
	"digitalaudio_cpm_default" numeric,
	"digitalaudio_cpc_default" numeric,
	"digitalaudio_cpv_default" numeric,
	"digitalaudio_ctr_default" numeric,
	"digitalaudio_vtr_default" numeric,
	"digitalaudio_frequency_default" numeric,
	"bvod_cpm_default" numeric,
	"bvod_cpc_default" numeric,
	"bvod_cpv_default" numeric,
	"bvod_ctr_default" numeric,
	"bvod_vtr_default" numeric,
	"bvod_frequency_default" numeric,
	"search_cpm_default" numeric,
	"search_cpc_default" numeric,
	"search_cpv_default" numeric,
	"search_ctr_default" numeric,
	"search_vtr_default" numeric,
	"search_frequency_default" numeric,
	"socialmedia_cpm_default" numeric,
	"socialmedia_cpc_default" numeric,
	"socialmedia_cpv_default" numeric,
	"socialmedia_ctr_default" numeric,
	"socialmedia_vtr_default" numeric,
	"socialmedia_frequency_default" numeric,
	"progdisplay_cpm_default" numeric,
	"progdisplay_cpc_default" numeric,
	"progdisplay_cpv_default" numeric,
	"progdisplay_ctr_default" numeric,
	"progdisplay_vtr_default" numeric,
	"progdisplay_frequency_default" numeric,
	"progvideo_cpm_default" numeric,
	"progvideo_cpc_default" numeric,
	"progvideo_cpv_default" numeric,
	"progvideo_ctr_default" numeric,
	"progvideo_vtr_default" numeric,
	"progvideo_frequency_default" numeric,
	"progbvod_cpm_default" numeric,
	"progbvod_cpc_default" numeric,
	"progbvod_cpv_default" numeric,
	"progbvod_ctr_default" numeric,
	"progbvod_vtr_default" numeric,
	"progbvod_frequency_default" numeric,
	"progaudio_cpm_default" numeric,
	"progaudio_cpc_default" numeric,
	"progaudio_cpv_default" numeric,
	"progaudio_ctr_default" numeric,
	"progaudio_vtr_default" numeric,
	"progaudio_frequency_default" numeric,
	"publisher_colour" text,
	"best_practice" jsonb
);
--> statement-breakpoint
CREATE TABLE "radio_stations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "radio_stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"station" text,
	"network" text
);
--> statement-breakpoint
CREATE TABLE "revenue_forecast_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revenue_forecast_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"fy" text,
	"line_key" text,
	"month" text,
	"amount" numeric,
	"updated_by" text,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "revenue_line_catalog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revenue_line_catalog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"line_key" text,
	"label" text,
	"fee_pct" numeric,
	"booked_mapping" jsonb,
	"sort_order" bigint,
	"active" boolean
);
--> statement-breakpoint
CREATE TABLE "scope_of_work" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scope_of_work_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_name" text,
	"contact_name" text,
	"contact_email" text,
	"scope_date" date,
	"scope_version" bigint,
	"project_name" text,
	"project_status" text,
	"project_overview" text,
	"deliverables" text,
	"tasks_steps" text,
	"timelines" text,
	"responsibilities" text,
	"requirements" text,
	"assumptions" text,
	"exclusions" text,
	"cost" jsonb,
	"payment_terms_and_conditions" text,
	"scope_id" text,
	"billing_schedule" jsonb
);
--> statement-breakpoint
CREATE TABLE "task_checklist_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_checklist_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_id" bigint,
	"label" text,
	"done" boolean,
	"sort" bigint
);
--> statement-breakpoint
CREATE TABLE "task_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_id" bigint,
	"user_id" bigint,
	"body" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_template_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_template_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"template_id" bigint,
	"label" text,
	"sort" bigint
);
--> statement-breakpoint
CREATE TABLE "task_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"mba_number" text,
	"title" text,
	"description" text,
	"status" text,
	"priority" text,
	"assignee_user_id" bigint,
	"due_date" timestamp with time zone,
	"recurring_rule" text,
	"template_id" bigint,
	"client_visible" boolean,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "tv_stations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tv_stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"station" text
);
--> statement-breakpoint
CREATE TABLE "video_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "xero_ap_bills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_ap_bills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"xero_contact_id" text,
	"status" text,
	"sub_total" numeric,
	"total_tax" numeric,
	"total" numeric,
	"amount_paid" numeric,
	"amount_due" numeric,
	"currency" text,
	"issue_date" date,
	"due_date" date,
	"fully_paid_date" date,
	"activity_month" date,
	"reference_raw" text,
	"line_items_json" jsonb,
	"pdf_file" jsonb,
	"xero_updated_utc" timestamp with time zone,
	"last_synced_at" timestamp with time zone,
	"raw_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "xero_ar_invoices" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_ar_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"xero_contact_id" text,
	"status" text,
	"sub_total" numeric,
	"total_tax" numeric,
	"total" numeric,
	"amount_paid" numeric,
	"amount_due" numeric,
	"currency" text,
	"issue_date" date,
	"due_date" date,
	"fully_paid_date" date,
	"reference_raw" text,
	"mba_number" text,
	"mba_match_id" bigint,
	"line_items_json" jsonb,
	"pdf_file" jsonb,
	"xero_updated_utc" timestamp with time zone,
	"last_synced_at" timestamp with time zone,
	"raw_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "xero_contacts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_contacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_contact_id" text,
	"name" text,
	"role" text,
	"email" text,
	"raw_json" jsonb,
	"synced_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "xero_sync_exceptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_sync_exceptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"reference" text,
	"reason" text,
	"raw_json" jsonb,
	"resolved" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"issue_date" text
);
--> statement-breakpoint
CREATE TABLE "xero_sync_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_sync_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"run_started_at" timestamp with time zone,
	"run_finished_at" timestamp with time zone,
	"status" text,
	"watermark_used" timestamp with time zone,
	"new_watermark" timestamp with time zone,
	"invoices_upserted" bigint,
	"contacts_upserted" bigint,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "billing_overrides" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"line_item_id" text NOT NULL,
	"component" "schedule_component" NOT NULL,
	"mode" text DEFAULT 'manual',
	"reason" text,
	"months" jsonb,
	"date_basis" text,
	CONSTRAINT "billing_overrides_version_id_line_item_id_component_unique" UNIQUE("version_id","line_item_id","component")
);
--> statement-breakpoint
CREATE TABLE "line_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "line_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"channel" "line_channel" NOT NULL,
	"line_item_id" text NOT NULL,
	"position" integer,
	"market" text,
	"buying_demo" text,
	"buy_type" text,
	"publisher" text,
	"platform" text,
	"bid_strategy" text,
	"fixed_cost_media" boolean,
	"client_pays_for_media" boolean,
	"budget_includes_fees" boolean,
	"no_adserving" boolean,
	"bursts" jsonb,
	"attrs" jsonb,
	CONSTRAINT "line_items_version_id_line_item_id_unique" UNIQUE("version_id","line_item_id")
);
--> statement-breakpoint
CREATE TABLE "mba_fee_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mba_fee_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"fees" jsonb NOT NULL,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mba_fee_snapshots_version_id_unique" UNIQUE("version_id")
);
--> statement-breakpoint
CREATE TABLE "media_plan_masters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_plan_masters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mba_number" text NOT NULL,
	"client_id" bigint,
	"mp_client_name" text,
	"campaign_name" text,
	"campaign_status" text,
	"campaign_start_date" date,
	"campaign_end_date" date,
	"campaign_budget_cents" bigint,
	"published_version_id" bigint,
	CONSTRAINT "media_plan_masters_mba_number_unique" UNIQUE("mba_number")
);
--> statement-breakpoint
CREATE TABLE "media_plan_versions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_plan_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"master_id" bigint NOT NULL,
	"version_number" integer NOT NULL,
	"mba_number" text NOT NULL,
	"campaign_name" text,
	"campaign_status" text,
	"campaign_start_date" date,
	"campaign_end_date" date,
	"brand" text,
	"client_contact" text,
	"po_number" text,
	"campaign_budget_cents" bigint,
	"fixed_fee" boolean,
	"channel_flags" jsonb,
	"legacy_schedules" jsonb,
	"media_plan_file" jsonb,
	"mba_pdf_file" jsonb,
	"aa_media_plan_file" jsonb,
	CONSTRAINT "media_plan_versions_master_id_version_number_unique" UNIQUE("master_id","version_number")
);
--> statement-breakpoint
CREATE TABLE "schedule_months" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_months_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"line_item_id" text NOT NULL,
	"component" "schedule_component" NOT NULL,
	"basis" "schedule_basis" NOT NULL,
	"month" date NOT NULL,
	"amount_cents" bigint NOT NULL,
	"source" "schedule_source" DEFAULT 'computed' NOT NULL,
	CONSTRAINT "schedule_months_version_id_line_item_id_component_basis_month_unique" UNIQUE("version_id","line_item_id","component","basis","month")
);
--> statement-breakpoint
ALTER TABLE "billing_overrides" ADD CONSTRAINT "billing_overrides_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_items" ADD CONSTRAINT "line_items_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mba_fee_snapshots" ADD CONSTRAINT "mba_fee_snapshots_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_masters" ADD CONSTRAINT "media_plan_masters_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_masters" ADD CONSTRAINT "fk_masters_published_version" FOREIGN KEY ("published_version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_versions" ADD CONSTRAINT "media_plan_versions_master_id_media_plan_masters_id_fk" FOREIGN KEY ("master_id") REFERENCES "public"."media_plan_masters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_months" ADD CONSTRAINT "schedule_months_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_audio_site_created_at" ON "audio_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_bvod_site_created_at" ON "bvod_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_campaign_kpi_created_at" ON "campaign_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_client_domains_client_id" ON "client_domains" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "idx_client_domains_email_domain" ON "client_domains" USING btree ("email_domain");--> statement-breakpoint
CREATE INDEX "idx_client_kpi_created_at" ON "client_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_client_notes_client_id" ON "client_notes" USING btree ("client_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_client_notes_fireflies_meeting_id" ON "client_notes" USING btree ("fireflies_meeting_id");--> statement-breakpoint
CREATE INDEX "idx_creative_asset_created_at" ON "creative_asset" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_creative_asset_mba_number" ON "creative_asset" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_display_site_created_at" ON "display_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_line_items_created_at" ON "finance_billing_line_items" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_line_items_finance_billing_records_id_line_item_id" ON "finance_billing_line_items" USING btree ("finance_billing_records_id","line_item_id");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_records_created_at" ON "finance_billing_records" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_finance_billing_records_invoice_key" ON "finance_billing_records" USING btree ("invoice_key");--> statement-breakpoint
CREATE INDEX "idx_finance_edits_created_at" ON "finance_edits" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_finance_saved_views_created_at" ON "finance_saved_views" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_magazines_created_at" ON "magazines" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_magazines_adsizes_created_at" ON "magazines_adsizes" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_media_container_best_practice_media_container" ON "media_container_best_practice" USING btree ("media_container");--> statement-breakpoint
CREATE INDEX "idx_newspaper_adsizes_created_at" ON "newspaper_adsizes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_newspapers_created_at" ON "newspapers" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_planning_audiences_clients_id" ON "planning_audiences" USING btree ("clients_id");--> statement-breakpoint
CREATE INDEX "idx_planning_audiences_mba_number" ON "planning_audiences" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_publisher_kpi_created_at" ON "publisher_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_radio_stations_created_at" ON "radio_stations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_revenue_forecast_lines_clients_id" ON "revenue_forecast_lines" USING btree ("clients_id");--> statement-breakpoint
CREATE INDEX "idx_revenue_forecast_lines_fy" ON "revenue_forecast_lines" USING btree ("fy");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_revenue_line_catalog_line_key" ON "revenue_line_catalog" USING btree ("line_key");--> statement-breakpoint
CREATE INDEX "idx_scope_of_work_created_at" ON "scope_of_work" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_task_checklist_items_task_id" ON "task_checklist_items" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_comments_task_id" ON "task_comments" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_template_items_template_id" ON "task_template_items" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "idx_tasks_client_id_status" ON "tasks" USING btree ("client_id","status");--> statement-breakpoint
CREATE INDEX "idx_tasks_assignee_user_id_due_date" ON "tasks" USING btree ("assignee_user_id","due_date");--> statement-breakpoint
CREATE INDEX "idx_tv_stations_created_at" ON "tv_stations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_video_site_created_at" ON "video_site" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_ap_bills_xero_invoice_id" ON "xero_ap_bills" USING btree ("xero_invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_ar_invoices_xero_invoice_id" ON "xero_ar_invoices" USING btree ("xero_invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_contacts_xero_contact_id" ON "xero_contacts" USING btree ("xero_contact_id");--> statement-breakpoint
CREATE INDEX "idx_line_items_version" ON "line_items" USING btree ("version_id");--> statement-breakpoint
CREATE INDEX "idx_line_items_channel" ON "line_items" USING btree ("channel");--> statement-breakpoint
CREATE INDEX "idx_line_items_line_item_id" ON "line_items" USING btree ("line_item_id");--> statement-breakpoint
CREATE INDEX "idx_schedule_months_version" ON "schedule_months" USING btree ("version_id");--> statement-breakpoint
CREATE INDEX "idx_schedule_months_month" ON "schedule_months" USING btree ("month");