CREATE TYPE "public"."finance_period_status" AS ENUM('open', 'pre_run_review', 'run', 'review', 'locked', 'invoiced', 'reconciled');--> statement-breakpoint
CREATE TYPE "public"."finance_run_item_status" AS ENUM('pending', 'approved', 'adjusted', 'held', 'excluded', 'stale');--> statement-breakpoint
CREATE TYPE "public"."finance_run_source" AS ENUM('media', 'retainer', 'sow');--> statement-breakpoint
CREATE TYPE "public"."line_channel" AS ENUM('television', 'radio', 'cinema', 'newspaper', 'magazines', 'ooh', 'prog_display', 'prog_video', 'prog_audio', 'prog_bvod', 'prog_ooh', 'digi_display', 'digi_video', 'digi_audio', 'digi_bvod', 'social', 'search', 'influencers', 'integrations', 'production');--> statement-breakpoint
CREATE TYPE "public"."schedule_basis" AS ENUM('billing', 'delivery');--> statement-breakpoint
CREATE TYPE "public"."schedule_component" AS ENUM('media', 'fee', 'adserving');--> statement-breakpoint
CREATE TYPE "public"."schedule_source" AS ENUM('computed', 'override');--> statement-breakpoint
CREATE TYPE "public"."xero_match_method" AS ENUM('reference', 'heuristic', 'manual');--> statement-breakpoint
CREATE TYPE "public"."xero_match_status" AS ENUM('matched', 'diverged', 'disputed', 'written_off');--> statement-breakpoint
CREATE TABLE "audio_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audio_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "bvod_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bvod_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "campaign_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mp_client_name" text,
	"mba_number" text,
	"version_number" bigint,
	"campaign_name" text,
	"media_type" text,
	"publisher" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric,
	"line_item_id" text
);
--> statement-breakpoint
CREATE TABLE "client_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mp_client_name" text,
	"publisher_name" text,
	"media_type" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric
);
--> statement-breakpoint
CREATE TABLE "clientdashboard" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clientdashboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_dashboard" text,
	"idgoogleads_dashboard" text,
	"idmeta_dashboard" text,
	"idcm360_dashboard" text,
	"iddv360_dashboard" text,
	"idtiktok_dashboard" text,
	"idlinkedin_dashboard" text,
	"idpinterest_dashboard" text,
	"idquantcast_dashboard" text,
	"idtaboola_dashboard" text,
	"idsnapchat_dashboard" text,
	"idbing_dashboard" text,
	"idvistar_dashboard" text,
	"idga4_dashboard" text,
	"idmerchantcentre_dashboard" text,
	"idshopify_dashboard" text
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mp_client_name" text,
	"clientcategory" text,
	"abn" text,
	"mbaidentifier" text,
	"legalbusinessname" text,
	"streetaddress" text,
	"suburb" text,
	"state_dropdown" text,
	"postcode" text,
	"keyfirstname" text,
	"keylastname" text,
	"keyphone" bigint,
	"keyemail" text,
	"billingfirstname" text,
	"billinglastname" text,
	"billingphone" bigint,
	"billingemail" text,
	"monthlyretainer" numeric,
	"retainer_end_month" date,
	"organicsocial" numeric,
	"television_checkbox" boolean,
	"radio_checkbox" boolean,
	"newspapers_checkbox" boolean,
	"magazines_checkbox" boolean,
	"ooh_checkbox" boolean,
	"cinema_checkbox" boolean,
	"digitaldisplay_checkbox" boolean,
	"digitalaudio_checkbox" boolean,
	"digitalvideo_checkbox" boolean,
	"bvod_checkbox" boolean,
	"feesocial" numeric,
	"feesearch" numeric,
	"feeprogdisplay" numeric,
	"feeprogvideo" numeric,
	"feeprogbvod" numeric,
	"feeprogaudio" numeric,
	"feeprogooh" numeric,
	"feecontentcreator" numeric,
	"adservvideo" numeric,
	"adservimp" numeric,
	"adservdisplay" numeric,
	"adservaudio" numeric,
	"idgoogleads" text,
	"idmeta" text,
	"idcm360" text,
	"iddv360" text,
	"idtiktok" text,
	"idlinkedin" text,
	"idpinterest" text,
	"idquantcast" text,
	"idtaboola" text,
	"idsnapchat" text,
	"idbing" text,
	"idvistar" text,
	"idga4" text,
	"idmerchantcentre" text,
	"idshopify" text,
	"payment_days" bigint,
	"payment_terms" text,
	"brand_colour" text,
	"client_logo" jsonb,
	"website" text,
	"facebook_url" text,
	"instagram_url" text,
	"linkedin_url" text,
	"tiktok_url" text,
	"client_brain" text,
	"client_brain_updated_at" timestamp with time zone,
	"slug" text,
	"sharepoint_site_url" text,
	"teams_group_id" text,
	"m365_is_anchor" boolean DEFAULT false NOT NULL,
	"client_name_aliases" jsonb DEFAULT '[]'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "creative_asset" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "creative_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mba_number" text,
	"media_plan_master_id" bigint,
	"line_item_id" text,
	"source_table" text,
	"asset_name" text,
	"original_filename" text,
	"mime_type" text,
	"file_size_bytes" bigint,
	"width_px" bigint,
	"height_px" bigint,
	"duration_seconds" numeric,
	"blob_url" text,
	"blob_pathname" text,
	"status" text,
	"uploaded_by_email" text,
	"uploaded_by_role" text
);
--> statement-breakpoint
CREATE TABLE "display_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "display_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "finance_billing_line_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_billing_line_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finance_billing_records_id" bigint,
	"item_code" text,
	"line_type" text,
	"media_type" text,
	"description" text,
	"publisher_name" text,
	"amount" numeric,
	"client_pays_media" boolean,
	"sort_order" bigint,
	"updated_at" timestamp with time zone,
	"line_item_id" text,
	"line_status" text,
	"received_at" timestamp with time zone,
	"received_amount" numeric,
	"note" text,
	"orphaned" boolean,
	"media_plan_version_number" bigint
);
--> statement-breakpoint
CREATE TABLE "finance_billing_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_billing_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"client_name" text,
	"billing_type" text,
	"mba_number" text,
	"campaign_name" text,
	"po_number" text,
	"billing_month" text,
	"invoice_date" date,
	"payment_days" bigint,
	"payment_terms" text,
	"status" text,
	"total" numeric,
	"has_pending_edits" boolean,
	"source_billing_schedule_id" bigint,
	"updated_at" timestamp with time zone,
	"billed" boolean,
	"billed_at" timestamp with time zone,
	"billed_by" bigint,
	"billed_amount_cents" bigint,
	"billed_lines_hash" text,
	"notes" text,
	"exported_at" timestamp with time zone,
	"exported_by" bigint,
	"invoice_key" text
);
--> statement-breakpoint
CREATE TABLE "finance_edits" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_edits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finance_billing_records_id" bigint,
	"finance_billing_line_items_id" bigint,
	"edit_type" text,
	"field_name" text,
	"old_value" text,
	"new_value" text,
	"edit_status" text,
	"edited_by" bigint,
	"edited_by_name" text,
	"published_at" timestamp with time zone,
	"record_type" text
);
--> statement-breakpoint
CREATE TABLE "finance_forecast_snapshot_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_forecast_snapshot_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"snapshot_id" bigint NOT NULL,
	"client_id" text NOT NULL,
	"client_name" text NOT NULL,
	"campaign_id" text,
	"mba_number" text,
	"media_plan_version_id" text,
	"version_number" bigint,
	"group_key" text NOT NULL,
	"line_key" text NOT NULL,
	"month_key" text NOT NULL,
	"amount" numeric NOT NULL,
	"fy_total" numeric NOT NULL,
	"source_hash" text,
	"source_debug_json" text
);
--> statement-breakpoint
CREATE TABLE "finance_forecast_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_forecast_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"snapshot_label" text NOT NULL,
	"snapshot_type" text NOT NULL,
	"financial_year" integer NOT NULL,
	"scenario" text NOT NULL,
	"taken_at" timestamp with time zone NOT NULL,
	"taken_by" text,
	"notes" text,
	"source_version_summary" text,
	"filter_context_json" text
);
--> statement-breakpoint
CREATE TABLE "finance_saved_views" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_saved_views_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" bigint,
	"view_name" text,
	"filters" jsonb,
	"is_default" boolean,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "magazines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "magazines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"title" text
);
--> statement-breakpoint
CREATE TABLE "magazines_adsizes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "magazines_adsizes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"adsize" text
);
--> statement-breakpoint
CREATE TABLE "media_container_best_practice" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_container_best_practice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"media_container" text,
	"best_practice" jsonb,
	"is_active" boolean,
	"_name" text
);
--> statement-breakpoint
CREATE TABLE "newspaper_adsizes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newspaper_adsizes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"adsize" text
);
--> statement-breakpoint
CREATE TABLE "newspapers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newspapers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"title" text
);
--> statement-breakpoint
CREATE TABLE "pacing_orphan_fixes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pacing_orphan_fixes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"admin_user_email" text,
	"channel" text,
	"platform_line_item_id" text,
	"previous_line_item_id" text,
	"new_line_item_id" text,
	"ad_group_name" text,
	"campaign_name" text,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "planning_audiences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planning_audiences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"mba_number" text,
	"name" text,
	"definition_json" jsonb,
	"composed_wc" numeric,
	"client_visible" boolean,
	"created_by_email" text
);
--> statement-breakpoint
CREATE TABLE "publisher_kpi" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "publisher_kpi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"publisher" text,
	"bid_strategy" text,
	"ctr" numeric,
	"cpv" numeric,
	"conversion_rate" numeric,
	"vtr" numeric,
	"frequency" numeric,
	"media_type" text
);
--> statement-breakpoint
CREATE TABLE "publishers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "publishers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"publisher_name" text,
	"publisherid" text,
	"publishertype" text,
	"billingagency" text,
	"financecode" text,
	"pub_television" boolean,
	"pub_radio" boolean,
	"pub_newspaper" boolean,
	"pub_magazines" boolean,
	"pub_ooh" boolean,
	"pub_cinema" boolean,
	"pub_digidisplay" boolean,
	"pub_digiaudio" boolean,
	"pub_digivideo" boolean,
	"pub_bvod" boolean,
	"pub_integration" boolean,
	"pub_search" boolean,
	"pub_socialmedia" boolean,
	"pub_progdisplay" boolean,
	"pub_progvideo" boolean,
	"pub_progbvod" boolean,
	"pub_progaudio" boolean,
	"pub_progooh" boolean,
	"pub_influencers" boolean,
	"radio_comms" numeric,
	"newspaper_comms" numeric,
	"television_comms" numeric,
	"magazines_comms" numeric,
	"ooh_comms" numeric,
	"cinema_comms" numeric,
	"digidisplay_comms" numeric,
	"digiaudio_comms" numeric,
	"digivideo_comms" numeric,
	"bvod_comms" numeric,
	"integration_comms" numeric,
	"search_comms" numeric,
	"progdisplay_comms" numeric,
	"progvideo_comms" numeric,
	"progbvod_comms" numeric,
	"progaudio_comms" numeric,
	"progooh_comms" numeric,
	"influencers_comms" numeric,
	"digitaldisplay_cpm_default" numeric,
	"digitaldisplay_cpc_default" numeric,
	"digitaldisplay_cpv_default" numeric,
	"digitaldisplay_ctr_default" numeric,
	"digitaldisplay_vtr_default" numeric,
	"digitaldisplay_frequency_default" numeric,
	"digitalvideo_cpm_default" numeric,
	"digitalvideo_cpc_default" numeric,
	"digitalvideo_cpv_default" numeric,
	"digitalvideo_ctr_default" numeric,
	"digitalvideo_vtr_default" numeric,
	"digitalvideo_frequency_default" numeric,
	"digitalaudio_cpm_default" numeric,
	"digitalaudio_cpc_default" numeric,
	"digitalaudio_cpv_default" numeric,
	"digitalaudio_ctr_default" numeric,
	"digitalaudio_vtr_default" numeric,
	"digitalaudio_frequency_default" numeric,
	"bvod_cpm_default" numeric,
	"bvod_cpc_default" numeric,
	"bvod_cpv_default" numeric,
	"bvod_ctr_default" numeric,
	"bvod_vtr_default" numeric,
	"bvod_frequency_default" numeric,
	"search_cpm_default" numeric,
	"search_cpc_default" numeric,
	"search_cpv_default" numeric,
	"search_ctr_default" numeric,
	"search_vtr_default" numeric,
	"search_frequency_default" numeric,
	"socialmedia_cpm_default" numeric,
	"socialmedia_cpc_default" numeric,
	"socialmedia_cpv_default" numeric,
	"socialmedia_ctr_default" numeric,
	"socialmedia_vtr_default" numeric,
	"socialmedia_frequency_default" numeric,
	"progdisplay_cpm_default" numeric,
	"progdisplay_cpc_default" numeric,
	"progdisplay_cpv_default" numeric,
	"progdisplay_ctr_default" numeric,
	"progdisplay_vtr_default" numeric,
	"progdisplay_frequency_default" numeric,
	"progvideo_cpm_default" numeric,
	"progvideo_cpc_default" numeric,
	"progvideo_cpv_default" numeric,
	"progvideo_ctr_default" numeric,
	"progvideo_vtr_default" numeric,
	"progvideo_frequency_default" numeric,
	"progbvod_cpm_default" numeric,
	"progbvod_cpc_default" numeric,
	"progbvod_cpv_default" numeric,
	"progbvod_ctr_default" numeric,
	"progbvod_vtr_default" numeric,
	"progbvod_frequency_default" numeric,
	"progaudio_cpm_default" numeric,
	"progaudio_cpc_default" numeric,
	"progaudio_cpv_default" numeric,
	"progaudio_ctr_default" numeric,
	"progaudio_vtr_default" numeric,
	"progaudio_frequency_default" numeric,
	"publisher_colour" text,
	"best_practice" jsonb
);
--> statement-breakpoint
CREATE TABLE "radio_stations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "radio_stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"station" text,
	"network" text
);
--> statement-breakpoint
CREATE TABLE "revenue_forecast_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revenue_forecast_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clients_id" bigint,
	"fy" text,
	"line_key" text,
	"month" text,
	"amount" numeric,
	"updated_by" text,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "revenue_line_catalog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revenue_line_catalog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"line_key" text,
	"label" text,
	"fee_pct" numeric,
	"booked_mapping" jsonb,
	"sort_order" bigint,
	"active" boolean
);
--> statement-breakpoint
CREATE TABLE "scope_of_work" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scope_of_work_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_name" text,
	"contact_name" text,
	"contact_email" text,
	"scope_date" date,
	"scope_version" bigint,
	"project_name" text,
	"project_status" text,
	"project_overview" text,
	"deliverables" text,
	"tasks_steps" text,
	"timelines" text,
	"responsibilities" text,
	"requirements" text,
	"assumptions" text,
	"exclusions" text,
	"cost" jsonb,
	"payment_terms_and_conditions" text,
	"scope_id" text,
	"billing_schedule" jsonb
);
--> statement-breakpoint
CREATE TABLE "tv_stations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tv_stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"network" text,
	"station" text
);
--> statement-breakpoint
CREATE TABLE "video_site" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_site_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"platform" text,
	"site" text
);
--> statement-breakpoint
CREATE TABLE "xero_ap_bills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_ap_bills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"xero_contact_id" text,
	"status" text,
	"sub_total" numeric,
	"total_tax" numeric,
	"total" numeric,
	"amount_paid" numeric,
	"amount_due" numeric,
	"currency" text,
	"issue_date" date,
	"due_date" date,
	"fully_paid_date" date,
	"activity_month" date,
	"reference_raw" text,
	"line_items_json" jsonb,
	"pdf_file" jsonb,
	"xero_updated_utc" timestamp with time zone,
	"last_synced_at" timestamp with time zone,
	"raw_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "xero_ar_invoices" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_ar_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"xero_contact_id" text,
	"status" text,
	"sub_total" numeric,
	"total_tax" numeric,
	"total" numeric,
	"amount_paid" numeric,
	"amount_due" numeric,
	"currency" text,
	"issue_date" date,
	"due_date" date,
	"fully_paid_date" date,
	"reference_raw" text,
	"mba_number" text,
	"mba_match_id" bigint,
	"line_items_json" jsonb,
	"pdf_file" jsonb,
	"xero_updated_utc" timestamp with time zone,
	"last_synced_at" timestamp with time zone,
	"raw_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "xero_client_aliases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_client_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"contact_key" text NOT NULL,
	"client_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xero_contacts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_contacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_contact_id" text,
	"name" text,
	"role" text,
	"email" text,
	"raw_json" jsonb,
	"synced_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "xero_sync_exceptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_sync_exceptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"xero_invoice_id" text,
	"invoice_number" text,
	"reference" text,
	"reason" text,
	"raw_json" jsonb,
	"resolved" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"issue_date" text
);
--> statement-breakpoint
CREATE TABLE "xero_sync_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_sync_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"run_started_at" timestamp with time zone,
	"run_finished_at" timestamp with time zone,
	"status" text,
	"watermark_used" timestamp with time zone,
	"new_watermark" timestamp with time zone,
	"invoices_upserted" bigint,
	"contacts_upserted" bigint,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "billing_overrides" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"line_item_id" text NOT NULL,
	"component" "schedule_component" NOT NULL,
	"mode" text DEFAULT 'manual',
	"reason" text,
	"months" jsonb,
	"date_basis" text,
	CONSTRAINT "billing_overrides_version_id_line_item_id_component_unique" UNIQUE("version_id","line_item_id","component")
);
--> statement-breakpoint
CREATE TABLE "line_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "line_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"channel" "line_channel" NOT NULL,
	"line_item_id" text NOT NULL,
	"position" integer,
	"market" text,
	"buying_demo" text,
	"buy_type" text,
	"publisher" text,
	"platform" text,
	"bid_strategy" text,
	"fixed_cost_media" boolean,
	"client_pays_for_media" boolean,
	"budget_includes_fees" boolean,
	"no_adserving" boolean,
	"bursts" jsonb,
	"attrs" jsonb,
	CONSTRAINT "line_items_version_id_line_item_id_unique" UNIQUE("version_id","line_item_id")
);
--> statement-breakpoint
CREATE TABLE "mba_fee_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mba_fee_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"fees" jsonb NOT NULL,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mba_fee_snapshots_version_id_unique" UNIQUE("version_id")
);
--> statement-breakpoint
CREATE TABLE "mba_line_approvals" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mba_line_approvals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mba_number" text NOT NULL,
	"media_plan_version" integer NOT NULL,
	"line_item_id" text NOT NULL,
	"media_type" text NOT NULL,
	"approved" boolean DEFAULT true NOT NULL,
	"approved_in_version" integer,
	CONSTRAINT "mba_line_approvals_mba_number_media_plan_version_line_item_id_media_type_unique" UNIQUE("mba_number","media_plan_version","line_item_id","media_type")
);
--> statement-breakpoint
CREATE TABLE "media_plan_masters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_plan_masters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mba_number" text NOT NULL,
	"client_id" bigint,
	"mp_client_name" text,
	"campaign_name" text,
	"campaign_status" text,
	"campaign_start_date" date,
	"campaign_end_date" date,
	"campaign_budget_cents" bigint,
	"published_version_id" bigint,
	CONSTRAINT "media_plan_masters_mba_number_unique" UNIQUE("mba_number")
);
--> statement-breakpoint
CREATE TABLE "media_plan_versions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_plan_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"master_id" bigint NOT NULL,
	"version_number" integer NOT NULL,
	"mba_number" text NOT NULL,
	"campaign_name" text,
	"campaign_status" text,
	"campaign_start_date" date,
	"campaign_end_date" date,
	"brand" text,
	"client_contact" text,
	"po_number" text,
	"campaign_budget_cents" bigint,
	"fixed_fee" boolean,
	"channel_flags" jsonb,
	"legacy_schedules" jsonb,
	"approved_slice" jsonb,
	"snapshot_checksum" text,
	"published_at" timestamp with time zone,
	"published_by" text,
	"mi_resolution" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"media_plan_file" jsonb,
	"mba_pdf_file" jsonb,
	"aa_media_plan_file" jsonb,
	CONSTRAINT "media_plan_versions_master_id_version_number_unique" UNIQUE("master_id","version_number")
);
--> statement-breakpoint
CREATE TABLE "schedule_months" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_months_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version_id" bigint NOT NULL,
	"line_item_id" text NOT NULL,
	"component" "schedule_component" NOT NULL,
	"basis" "schedule_basis" NOT NULL,
	"month" date NOT NULL,
	"amount_cents" bigint NOT NULL,
	"source" "schedule_source" DEFAULT 'computed' NOT NULL,
	CONSTRAINT "schedule_months_version_id_line_item_id_component_basis_month_unique" UNIQUE("version_id","line_item_id","component","basis","month")
);
--> statement-breakpoint
CREATE TABLE "assignment_rules" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "assignment_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"category" text NOT NULL,
	"assignee_email" text NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"confidence" numeric(4, 3),
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ava_task_proposals" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "ava_task_proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source_note_id" bigint,
	"client_id" bigint,
	"proposed_title" text NOT NULL,
	"proposed_description" text,
	"proposed_category" text,
	"proposed_due_date" timestamp with time zone,
	"proposed_assignee_email" text,
	"proposed_mba_number" text,
	"ava_confidence" numeric(4, 3),
	"ava_rationale" text,
	"status" text DEFAULT 'proposed' NOT NULL,
	"decided_by_email" text,
	"decided_at" timestamp with time zone,
	"created_task_id" bigint,
	"decision_diff" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "client_domains" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_domains_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"email_domain" text
);
--> statement-breakpoint
CREATE TABLE "client_notes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"mba_number" text,
	"source" text,
	"title" text,
	"body" text,
	"meeting_date" timestamp with time zone,
	"fireflies_meeting_id" text,
	"participants" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"organizer_email" text,
	"matched_by" text,
	"duration_seconds" integer,
	"transcript_url" text,
	"is_internal" boolean DEFAULT false NOT NULL,
	"attributed_type" text,
	"publisher_id" bigint
);
--> statement-breakpoint
CREATE TABLE "codex_activity" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "codex_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_type" text NOT NULL,
	"entity_id" bigint NOT NULL,
	"actor_email" text,
	"actor_kind" text DEFAULT 'user' NOT NULL,
	"action" text NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fireflies_sync_state" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "fireflies_sync_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"run_started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"run_finished_at" timestamp with time zone,
	"cursor_from" timestamp with time zone,
	"meetings_seen" integer DEFAULT 0 NOT NULL,
	"notes_created" integer DEFAULT 0 NOT NULL,
	"notes_skipped" integer DEFAULT 0 NOT NULL,
	"unmatched" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "task_checklist_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_checklist_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_id" bigint,
	"label" text,
	"done" boolean,
	"sort" bigint
);
--> statement-breakpoint
CREATE TABLE "task_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_id" bigint,
	"body" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"author_email" text,
	"author_name" text,
	"author_kind" text DEFAULT 'user' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_template_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_template_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"template_id" bigint,
	"label" text,
	"sort" bigint
);
--> statement-breakpoint
CREATE TABLE "task_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" bigint,
	"mba_number" text,
	"title" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'todo' NOT NULL,
	"priority" text DEFAULT 'normal',
	"assignee_email" text,
	"assignee_name" text,
	"due_date" timestamp with time zone,
	"recurring_rule" text,
	"template_id" bigint,
	"client_visible" boolean,
	"created_by_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"source" text DEFAULT 'manual' NOT NULL,
	"source_note_id" bigint,
	"category" text,
	"auto_created" boolean DEFAULT false NOT NULL,
	"ava_auto_key" text,
	"estimated_minutes" integer,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "team_members" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "team_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text NOT NULL,
	"role_title" text,
	"active" boolean DEFAULT true NOT NULL,
	"capacity_notes" text,
	"working_style" text,
	"default_client_ids" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email_aliases" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"auth0_user_id" text,
	"roster_source" text DEFAULT 'manual',
	"last_login_at" timestamp with time zone,
	CONSTRAINT "team_members_email_unique" UNIQUE("email"),
	CONSTRAINT "team_members_auth0_user_id_unique" UNIQUE("auth0_user_id")
);
--> statement-breakpoint
CREATE TABLE "migration_markers" (
	"key" text PRIMARY KEY NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "campaign_insights" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "campaign_insights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mba_number" text NOT NULL,
	"client_id" bigint NOT NULL,
	"period" text,
	"insight_type" text NOT NULL,
	"body" text NOT NULL,
	"source" text NOT NULL,
	"confidence" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"superseded_by" bigint,
	"superseded_at" timestamp with time zone,
	CONSTRAINT "campaign_insights_insight_type_check" CHECK ("campaign_insights"."insight_type" = ANY (ARRAY['delivery'::text, 'audience'::text, 'creative'::text, 'channel'::text, 'commercial'::text])),
	CONSTRAINT "campaign_insights_source_check" CHECK ("campaign_insights"."source" = ANY (ARRAY['ava'::text, 'human'::text])),
	CONSTRAINT "campaign_insights_mba_number_lowercase" CHECK ("campaign_insights"."mba_number" = lower("campaign_insights"."mba_number")),
	CONSTRAINT "campaign_insights_supersede_pair" CHECK (("campaign_insights"."superseded_by" IS NULL) = ("campaign_insights"."superseded_at" IS NULL)),
	CONSTRAINT "campaign_insights_no_self_supersede" CHECK (("campaign_insights"."superseded_by" IS NULL) OR ("campaign_insights"."superseded_by" <> "campaign_insights"."id"))
);
--> statement-breakpoint
CREATE TABLE "m365_provisioning_log" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "m365_provisioning_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_type" text NOT NULL,
	"entity_id" text,
	"action" text NOT NULL,
	"request_id" text,
	"actor" text,
	"outcome" text NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "m365_provisioning_log_outcome_check" CHECK ("m365_provisioning_log"."outcome" IN ('success', 'failure', 'skipped'))
);
--> statement-breakpoint
CREATE TABLE "line_item_panel_flights" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "line_item_panel_flights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"panel_id" bigint NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"is_live" boolean DEFAULT true NOT NULL,
	"is_bonus" boolean DEFAULT false NOT NULL,
	CONSTRAINT "line_item_panel_flights_panel_period_unique" UNIQUE("panel_id","period_start"),
	CONSTRAINT "line_item_panel_flights_period_order" CHECK ("line_item_panel_flights"."period_end" >= "line_item_panel_flights"."period_start")
);
--> statement-breakpoint
CREATE TABLE "line_item_panels" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "line_item_panels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"line_item_id" text NOT NULL,
	"mba_number" text NOT NULL,
	"buy_granularity" text NOT NULL,
	"latitude" numeric,
	"longitude" numeric,
	"publisher_format_name" text,
	"state" text,
	"site_number" text,
	"address_or_pack_details" text,
	"suburb" text,
	"postcode" text,
	"direction" text,
	"geography" text,
	"format" text,
	"size" text,
	"orientation" text,
	"digital_spec" text,
	"illumination" text,
	"digital_operating_hours" text,
	"rotation_seconds" numeric,
	"advertiser_share" numeric,
	"panel_name" text,
	"village_name" text,
	"panel_weight" numeric,
	"source_publisher" text,
	"source_row_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "line_item_panels_mba_number_lowercase" CHECK ("line_item_panels"."mba_number" = lower("line_item_panels"."mba_number")),
	CONSTRAINT "line_item_panels_buy_granularity_check" CHECK ("line_item_panels"."buy_granularity" = ANY (ARRAY['panel'::text, 'pack'::text]))
);
--> statement-breakpoint
CREATE TABLE "publisher_profiles" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "publisher_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publisher_name" text NOT NULL,
	"publisher_id" bigint,
	"media_type" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"detect_signature" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"column_map" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"grid_semantics" text NOT NULL,
	"line_granularity" text DEFAULT 'per_row' NOT NULL,
	"legend_map" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"sheet_rules" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publisher_profiles_publisher_name_unique" UNIQUE("publisher_name"),
	CONSTRAINT "publisher_profiles_grid_semantics_check" CHECK ("publisher_profiles"."grid_semantics" = ANY (ARRAY['status_matrix'::text, 'count'::text, 'currency'::text])),
	CONSTRAINT "publisher_profiles_line_granularity_check" CHECK ("publisher_profiles"."line_granularity" = ANY (ARRAY['per_row'::text, 'grouped'::text]))
);
--> statement-breakpoint
CREATE TABLE "ava_time_entry_proposals" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ava_time_entry_proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source_note_id" bigint NOT NULL,
	"member_email" text NOT NULL,
	"entry_date" date NOT NULL,
	"duration_minutes" integer NOT NULL,
	"note" text NOT NULL,
	"client_id" bigint,
	"mba_number" text,
	"myhours_project_id" text,
	"myhours_task_id" text,
	"status" text DEFAULT 'proposed' NOT NULL,
	"block_reason" text,
	"myhours_log_id" text,
	"confirmed_by_email" text,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "myhours_links" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "myhours_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"client_id" bigint,
	"mba_number" text,
	"myhours_id" text NOT NULL,
	"myhours_name" text,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "myhours_sync_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "myhours_sync_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"entries_upserted" integer DEFAULT 0 NOT NULL,
	"structures_created" integer DEFAULT 0 NOT NULL,
	"unmapped_count" integer DEFAULT 0 NOT NULL,
	"unknown_user_count" integer DEFAULT 0 NOT NULL,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "time_entries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "time_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"myhours_log_id" text NOT NULL,
	"member_email" text NOT NULL,
	"entry_date" date NOT NULL,
	"duration_minutes" integer NOT NULL,
	"note" text,
	"myhours_project_id" text,
	"myhours_project_name" text,
	"myhours_task_id" text,
	"myhours_task_name" text,
	"client_id" bigint,
	"mba_number" text,
	"mapping_source" text DEFAULT 'unmapped' NOT NULL,
	"raw" jsonb,
	"synced_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "spec_deadline_overrides" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "spec_deadline_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mba_number" text NOT NULL,
	"publisher_key" text NOT NULL,
	"derived_ymd" date NOT NULL,
	"override_ymd" date NOT NULL,
	"overridden_by" text NOT NULL,
	"overridden_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "spec_deadline_overrides_mba_publisher" UNIQUE("mba_number","publisher_key")
);
--> statement-breakpoint
CREATE TABLE "publisher_specs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "publisher_specs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publisher_slug" text NOT NULL,
	"publisher_id" bigint,
	"publisher_name" text NOT NULL,
	"spec_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"supply_deadline_min_days" integer,
	"supply_deadline_max_days" integer,
	"supply_deadline_business_days" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publisher_specs_slug_unique" UNIQUE("publisher_slug")
);
--> statement-breakpoint
CREATE TABLE "spec_runs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "spec_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publisher_specs_id" bigint,
	"publisher_id" bigint,
	"publisher_slug" text,
	"file_name" text,
	"uploaded_by" text,
	"blob_path" text,
	"extracted" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"outcome" text NOT NULL,
	"outcome_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingest_runs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "ingest_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publisher_id" bigint,
	"publisher_name" text,
	"file_name" text,
	"uploaded_by" text,
	"detected_confidence" numeric,
	"required_coverage" numeric,
	"line_item_count" integer DEFAULT 0 NOT NULL,
	"panel_count" integer DEFAULT 0 NOT NULL,
	"burst_count" integer DEFAULT 0 NOT NULL,
	"money_delta" numeric,
	"outcome" text NOT NULL,
	"outcome_reason" text,
	"accepted_version_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingest_stages" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "ingest_stages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"stage_id" uuid NOT NULL,
	"review_package" jsonb NOT NULL,
	"file_name" text,
	"uploaded_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"retained_at" timestamp with time zone,
	"master_id" bigint,
	"accepted_version_id" bigint,
	CONSTRAINT "ingest_stages_stage_id_unique" UNIQUE("stage_id")
);
--> statement-breakpoint
CREATE TABLE "meeting_title_rules" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "meeting_title_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"normalized_title" text NOT NULL,
	"target_type" text NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "meeting_title_rules_normalized_title_unique" UNIQUE("normalized_title")
);
--> statement-breakpoint
CREATE TABLE "publisher_domains" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "publisher_domains_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publisher_id" bigint NOT NULL,
	"email_domain" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publisher_domains_email_domain_unique" UNIQUE("email_domain")
);
--> statement-breakpoint
CREATE TABLE "app_notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"audience" text NOT NULL,
	"kind" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"read_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "finance_periods" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"period_month" date NOT NULL,
	"status" "finance_period_status" DEFAULT 'open' NOT NULL,
	"ran_at" timestamp with time zone,
	"locked_at" timestamp with time zone,
	"locked_by" text,
	"amended_after_lock" boolean DEFAULT false NOT NULL,
	"sheet_blob_pathname" text,
	"sheet_version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_finance_periods_period_month" UNIQUE("period_month")
);
--> statement-breakpoint
CREATE TABLE "finance_run_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_run_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"period_id" bigint NOT NULL,
	"source" "finance_run_source" NOT NULL,
	"natural_key" text NOT NULL,
	"mba_number" text,
	"client_id" bigint,
	"version_id" bigint,
	"sow_id" bigint,
	"line_items_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"amount_cents" bigint DEFAULT 0 NOT NULL,
	"invoice_reference" text NOT NULL,
	"status" "finance_run_item_status" DEFAULT 'pending' NOT NULL,
	"adjustment_cents" bigint,
	"adjustment_reason" text,
	"hold_reason" text,
	"exclude_reason" text,
	"client_snapshot_json" jsonb,
	"linked_variance_from_item_id" bigint,
	"rolled_from_item_id" bigint,
	CONSTRAINT "uq_finance_run_items_period_source_key" UNIQUE("period_id","source","natural_key")
);
--> statement-breakpoint
CREATE TABLE "xero_contact_links" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_contact_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"xero_contact_key" text NOT NULL,
	"client_id" bigint NOT NULL,
	"learned_from" text,
	CONSTRAINT "uq_xero_contact_links_key" UNIQUE("xero_contact_key")
);
--> statement-breakpoint
CREATE TABLE "xero_invoice_matches" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xero_invoice_matches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"xero_invoice_id" text NOT NULL,
	"run_item_id" bigint,
	"method" "xero_match_method" NOT NULL,
	"confidence" numeric(5, 4) DEFAULT '0' NOT NULL,
	"delta_cents" bigint DEFAULT 0 NOT NULL,
	"status" "xero_match_status" DEFAULT 'matched' NOT NULL,
	"decided_by" text,
	"decided_at" timestamp with time zone,
	"card_kind" text,
	"detail" text,
	"period_month" date,
	CONSTRAINT "uq_xero_invoice_matches_invoice" UNIQUE("xero_invoice_id")
);
--> statement-breakpoint
CREATE TABLE "xero_match_month_metrics" (
	"period_month" date PRIMARY KEY NOT NULL,
	"reference_attempts" integer DEFAULT 0 NOT NULL,
	"reference_hits" integer DEFAULT 0 NOT NULL,
	"reference_hit_rate" numeric(7, 6) DEFAULT '0' NOT NULL,
	"tier1_matched" integer DEFAULT 0 NOT NULL,
	"tier1_diverged" integer DEFAULT 0 NOT NULL,
	"tier2_suggested" integer DEFAULT 0 NOT NULL,
	"duplicates" integer DEFAULT 0 NOT NULL,
	"orphans" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plan_working_drafts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plan_working_drafts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"master_id" bigint NOT NULL,
	"user_id" text NOT NULL,
	"user_label" text,
	"base_version_id" bigint,
	"draft_state_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "uq_plan_working_drafts_master_user" UNIQUE("master_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "finance_forecast_snapshot_lines" ADD CONSTRAINT "finance_forecast_snapshot_lines_snapshot_id_finance_forecast_snapshots_id_fk" FOREIGN KEY ("snapshot_id") REFERENCES "public"."finance_forecast_snapshots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xero_client_aliases" ADD CONSTRAINT "xero_client_aliases_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_overrides" ADD CONSTRAINT "billing_overrides_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_items" ADD CONSTRAINT "line_items_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mba_fee_snapshots" ADD CONSTRAINT "mba_fee_snapshots_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_masters" ADD CONSTRAINT "media_plan_masters_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_masters" ADD CONSTRAINT "fk_masters_published_version" FOREIGN KEY ("published_version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_plan_versions" ADD CONSTRAINT "media_plan_versions_master_id_media_plan_masters_id_fk" FOREIGN KEY ("master_id") REFERENCES "public"."media_plan_masters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_months" ADD CONSTRAINT "schedule_months_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ava_task_proposals" ADD CONSTRAINT "ava_task_proposals_source_note_id_fkey" FOREIGN KEY ("source_note_id") REFERENCES "public"."client_notes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ava_task_proposals" ADD CONSTRAINT "ava_task_proposals_created_task_id_fkey" FOREIGN KEY ("created_task_id") REFERENCES "public"."tasks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_notes" ADD CONSTRAINT "client_notes_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_checklist_items" ADD CONSTRAINT "fk_task_checklist_items_task" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_comments" ADD CONSTRAINT "fk_task_comments_task" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_template_items" ADD CONSTRAINT "fk_task_template_items_template" FOREIGN KEY ("template_id") REFERENCES "public"."task_templates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_template" FOREIGN KEY ("template_id") REFERENCES "public"."task_templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_source_note_id_fkey" FOREIGN KEY ("source_note_id") REFERENCES "public"."client_notes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_insights" ADD CONSTRAINT "campaign_insights_superseded_by_fkey" FOREIGN KEY ("superseded_by") REFERENCES "public"."campaign_insights"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "line_item_panel_flights" ADD CONSTRAINT "line_item_panel_flights_panel_id_line_item_panels_id_fk" FOREIGN KEY ("panel_id") REFERENCES "public"."line_item_panels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publisher_profiles" ADD CONSTRAINT "publisher_profiles_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ava_time_entry_proposals" ADD CONSTRAINT "ava_time_entry_proposals_source_note_id_fkey" FOREIGN KEY ("source_note_id") REFERENCES "public"."client_notes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publisher_specs" ADD CONSTRAINT "publisher_specs_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "spec_runs" ADD CONSTRAINT "spec_runs_publisher_specs_id_publisher_specs_id_fk" FOREIGN KEY ("publisher_specs_id") REFERENCES "public"."publisher_specs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "spec_runs" ADD CONSTRAINT "spec_runs_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingest_runs" ADD CONSTRAINT "ingest_runs_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publisher_domains" ADD CONSTRAINT "publisher_domains_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_run_items" ADD CONSTRAINT "finance_run_items_period_id_finance_periods_id_fk" FOREIGN KEY ("period_id") REFERENCES "public"."finance_periods"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_run_items" ADD CONSTRAINT "finance_run_items_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_run_items" ADD CONSTRAINT "finance_run_items_version_id_media_plan_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_run_items" ADD CONSTRAINT "finance_run_items_linked_variance_from_item_id_finance_run_items_id_fk" FOREIGN KEY ("linked_variance_from_item_id") REFERENCES "public"."finance_run_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_run_items" ADD CONSTRAINT "finance_run_items_rolled_from_item_id_finance_run_items_id_fk" FOREIGN KEY ("rolled_from_item_id") REFERENCES "public"."finance_run_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xero_contact_links" ADD CONSTRAINT "xero_contact_links_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xero_invoice_matches" ADD CONSTRAINT "xero_invoice_matches_run_item_id_finance_run_items_id_fk" FOREIGN KEY ("run_item_id") REFERENCES "public"."finance_run_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plan_working_drafts" ADD CONSTRAINT "plan_working_drafts_master_id_media_plan_masters_id_fk" FOREIGN KEY ("master_id") REFERENCES "public"."media_plan_masters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plan_working_drafts" ADD CONSTRAINT "plan_working_drafts_base_version_id_media_plan_versions_id_fk" FOREIGN KEY ("base_version_id") REFERENCES "public"."media_plan_versions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_audio_site_created_at" ON "audio_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_bvod_site_created_at" ON "bvod_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_campaign_kpi_created_at" ON "campaign_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_client_kpi_created_at" ON "client_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_clients_m365_anchor_mbaidentifier" ON "clients" USING btree (lower(btrim("mbaidentifier"))) WHERE "clients"."m365_is_anchor" AND "clients"."mbaidentifier" IS NOT NULL AND btrim("clients"."mbaidentifier") <> '';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_clients_slug_lower" ON "clients" USING btree (lower(btrim("slug"))) WHERE "clients"."slug" IS NOT NULL AND btrim("clients"."slug") <> '';--> statement-breakpoint
CREATE INDEX "idx_creative_asset_created_at" ON "creative_asset" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_creative_asset_mba_number" ON "creative_asset" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_display_site_created_at" ON "display_site" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_line_items_created_at" ON "finance_billing_line_items" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_line_items_finance_billing_records_id_line_item_id" ON "finance_billing_line_items" USING btree ("finance_billing_records_id","line_item_id");--> statement-breakpoint
CREATE INDEX "idx_finance_billing_records_created_at" ON "finance_billing_records" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_finance_billing_records_invoice_key" ON "finance_billing_records" USING btree ("invoice_key");--> statement-breakpoint
CREATE INDEX "idx_finance_edits_created_at" ON "finance_edits" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_ffsl_snapshot_client_line_month" ON "finance_forecast_snapshot_lines" USING btree ("snapshot_id","client_id","line_key","month_key");--> statement-breakpoint
CREATE INDEX "idx_ffsl_snapshot_group_line_month" ON "finance_forecast_snapshot_lines" USING btree ("snapshot_id","group_key","line_key","month_key");--> statement-breakpoint
CREATE INDEX "idx_ffsl_snapshot_month" ON "finance_forecast_snapshot_lines" USING btree ("snapshot_id","month_key");--> statement-breakpoint
CREATE INDEX "idx_finance_forecast_snapshots_fy_scenario_taken" ON "finance_forecast_snapshots" USING btree ("financial_year","scenario","taken_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_finance_saved_views_created_at" ON "finance_saved_views" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_magazines_created_at" ON "magazines" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_magazines_adsizes_created_at" ON "magazines_adsizes" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_media_container_best_practice_media_container" ON "media_container_best_practice" USING btree ("media_container");--> statement-breakpoint
CREATE INDEX "idx_newspaper_adsizes_created_at" ON "newspaper_adsizes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_newspapers_created_at" ON "newspapers" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_planning_audiences_clients_id" ON "planning_audiences" USING btree ("clients_id");--> statement-breakpoint
CREATE INDEX "idx_planning_audiences_mba_number" ON "planning_audiences" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_publisher_kpi_created_at" ON "publisher_kpi" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_radio_stations_created_at" ON "radio_stations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_revenue_forecast_lines_clients_id" ON "revenue_forecast_lines" USING btree ("clients_id");--> statement-breakpoint
CREATE INDEX "idx_revenue_forecast_lines_fy" ON "revenue_forecast_lines" USING btree ("fy");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_revenue_forecast_lines_natural_key" ON "revenue_forecast_lines" USING btree ("clients_id","fy","line_key","month");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_revenue_line_catalog_line_key" ON "revenue_line_catalog" USING btree ("line_key");--> statement-breakpoint
CREATE INDEX "idx_scope_of_work_created_at" ON "scope_of_work" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_tv_stations_created_at" ON "tv_stations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_video_site_created_at" ON "video_site" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_ap_bills_xero_invoice_id" ON "xero_ap_bills" USING btree ("xero_invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_ar_invoices_xero_invoice_id" ON "xero_ar_invoices" USING btree ("xero_invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_client_aliases_contact_key" ON "xero_client_aliases" USING btree ("contact_key");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xero_contacts_xero_contact_id" ON "xero_contacts" USING btree ("xero_contact_id");--> statement-breakpoint
CREATE INDEX "idx_line_items_version" ON "line_items" USING btree ("version_id");--> statement-breakpoint
CREATE INDEX "idx_line_items_channel" ON "line_items" USING btree ("channel");--> statement-breakpoint
CREATE INDEX "idx_line_items_line_item_id" ON "line_items" USING btree ("line_item_id");--> statement-breakpoint
CREATE INDEX "idx_mba_line_approvals_mba_version" ON "mba_line_approvals" USING btree ("mba_number","media_plan_version");--> statement-breakpoint
CREATE INDEX "idx_mba_line_approvals_line_item_id" ON "mba_line_approvals" USING btree ("line_item_id");--> statement-breakpoint
CREATE INDEX "idx_mpv_published_at" ON "media_plan_versions" USING btree ("published_at") WHERE "media_plan_versions"."published_at" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_mpv_master_published" ON "media_plan_versions" USING btree ("master_id","published_at" DESC NULLS LAST) WHERE "media_plan_versions"."published_at" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_schedule_months_version" ON "schedule_months" USING btree ("version_id");--> statement-breakpoint
CREATE INDEX "idx_schedule_months_month" ON "schedule_months" USING btree ("month");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_assignment_rules_scope" ON "assignment_rules" USING btree (COALESCE("client_id", 0),"category") WHERE "assignment_rules"."active";--> statement-breakpoint
CREATE INDEX "idx_ava_task_proposals_status_created" ON "ava_task_proposals" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "idx_ava_task_proposals_client" ON "ava_task_proposals" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "idx_ava_task_proposals_mba" ON "ava_task_proposals" USING btree ("proposed_mba_number") WHERE "ava_task_proposals"."proposed_mba_number" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_client_domains_client_id" ON "client_domains" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "idx_client_domains_email_domain" ON "client_domains" USING btree ("email_domain");--> statement-breakpoint
CREATE INDEX "idx_client_notes_client_id" ON "client_notes" USING btree ("client_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_client_notes_fireflies_meeting_id" ON "client_notes" USING btree ("fireflies_meeting_id");--> statement-breakpoint
CREATE INDEX "idx_client_notes_attributed_type" ON "client_notes" USING btree ("attributed_type");--> statement-breakpoint
CREATE INDEX "idx_client_notes_publisher_id" ON "client_notes" USING btree ("publisher_id");--> statement-breakpoint
CREATE INDEX "idx_codex_activity_entity" ON "codex_activity" USING btree ("entity_type","entity_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_task_checklist_items_task_id" ON "task_checklist_items" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_comments_task_id" ON "task_comments" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_template_items_template_id" ON "task_template_items" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "idx_tasks_client_id_status" ON "tasks" USING btree ("client_id","status");--> statement-breakpoint
CREATE INDEX "idx_tasks_assignee_email_due_date" ON "tasks" USING btree ("assignee_email","due_date");--> statement-breakpoint
CREATE INDEX "idx_tasks_source_note_id" ON "tasks" USING btree ("source_note_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_tasks_ava_auto_key" ON "tasks" USING btree ("ava_auto_key") WHERE "tasks"."ava_auto_key" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_campaign_insights_client_created" ON "campaign_insights" USING btree ("client_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_campaign_insights_mba" ON "campaign_insights" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_campaign_insights_live" ON "campaign_insights" USING btree ("client_id","created_at" DESC NULLS LAST) WHERE "campaign_insights"."superseded_by" IS NULL;--> statement-breakpoint
CREATE INDEX "idx_campaign_insights_body_fts" ON "campaign_insights" USING gin (to_tsvector('english'::regconfig, "body"));--> statement-breakpoint
CREATE INDEX "idx_m365_provisioning_log_created" ON "m365_provisioning_log" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_m365_provisioning_log_entity" ON "m365_provisioning_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "idx_m365_provisioning_log_request" ON "m365_provisioning_log" USING btree ("request_id") WHERE "m365_provisioning_log"."request_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_line_item_panel_flights_panel_id" ON "line_item_panel_flights" USING btree ("panel_id");--> statement-breakpoint
CREATE INDEX "idx_line_item_panel_flights_period_start" ON "line_item_panel_flights" USING btree ("period_start");--> statement-breakpoint
CREATE INDEX "idx_line_item_panels_mba" ON "line_item_panels" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_line_item_panels_line_item_id" ON "line_item_panels" USING btree ("line_item_id");--> statement-breakpoint
CREATE INDEX "idx_publisher_profiles_media_type" ON "publisher_profiles" USING btree ("media_type");--> statement-breakpoint
CREATE INDEX "idx_publisher_profiles_active" ON "publisher_profiles" USING btree ("active") WHERE "publisher_profiles"."active" = true;--> statement-breakpoint
CREATE INDEX "idx_publisher_profiles_publisher_id" ON "publisher_profiles" USING btree ("publisher_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ava_time_entry_proposals_note_member_unique" ON "ava_time_entry_proposals" USING btree ("source_note_id","member_email");--> statement-breakpoint
CREATE UNIQUE INDEX "ava_time_entry_proposals_log_id_unique" ON "ava_time_entry_proposals" USING btree ("myhours_log_id");--> statement-breakpoint
CREATE INDEX "idx_ava_time_entry_proposals_week" ON "ava_time_entry_proposals" USING btree ("entry_date","status");--> statement-breakpoint
CREATE INDEX "idx_ava_time_entry_proposals_member" ON "ava_time_entry_proposals" USING btree ("member_email","entry_date");--> statement-breakpoint
CREATE UNIQUE INDEX "myhours_links_kind_myhours_id_unique" ON "myhours_links" USING btree ("kind","myhours_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_myhours_links_kind_mba_unique" ON "myhours_links" USING btree ("kind","mba_number") WHERE "myhours_links"."mba_number" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "time_entries_myhours_log_id_unique" ON "time_entries" USING btree ("myhours_log_id");--> statement-breakpoint
CREATE INDEX "idx_time_entries_member_email_entry_date" ON "time_entries" USING btree ("member_email","entry_date");--> statement-breakpoint
CREATE INDEX "idx_time_entries_mba_number" ON "time_entries" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_time_entries_client_id" ON "time_entries" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "idx_spec_deadline_overrides_mba" ON "spec_deadline_overrides" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_publisher_specs_publisher_id" ON "publisher_specs" USING btree ("publisher_id");--> statement-breakpoint
CREATE INDEX "idx_spec_runs_publisher_specs_id" ON "spec_runs" USING btree ("publisher_specs_id");--> statement-breakpoint
CREATE INDEX "idx_spec_runs_created_at" ON "spec_runs" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_ingest_runs_publisher_id" ON "ingest_runs" USING btree ("publisher_id");--> statement-breakpoint
CREATE INDEX "idx_ingest_runs_created_at" ON "ingest_runs" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_ingest_stages_expires_at" ON "ingest_stages" USING btree ("expires_at") WHERE "ingest_stages"."retained_at" IS NULL AND "ingest_stages"."expires_at" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_ingest_stages_master_id" ON "ingest_stages" USING btree ("master_id") WHERE "ingest_stages"."master_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_ingest_stages_accepted_version_id" ON "ingest_stages" USING btree ("accepted_version_id") WHERE "ingest_stages"."accepted_version_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_publisher_domains_publisher_id" ON "publisher_domains" USING btree ("publisher_id");--> statement-breakpoint
CREATE INDEX "idx_app_notifications_audience_created" ON "app_notifications" USING btree ("audience","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_app_notifications_unread" ON "app_notifications" USING btree ("audience") WHERE "app_notifications"."read_at" IS NULL;--> statement-breakpoint
CREATE INDEX "idx_finance_periods_status" ON "finance_periods" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_finance_run_items_mba" ON "finance_run_items" USING btree ("mba_number");--> statement-breakpoint
CREATE INDEX "idx_finance_run_items_period" ON "finance_run_items" USING btree ("period_id");--> statement-breakpoint
CREATE INDEX "idx_finance_run_items_status" ON "finance_run_items" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_xero_contact_links_client" ON "xero_contact_links" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "idx_xero_invoice_matches_period" ON "xero_invoice_matches" USING btree ("period_month");--> statement-breakpoint
CREATE INDEX "idx_xero_invoice_matches_run_item" ON "xero_invoice_matches" USING btree ("run_item_id");--> statement-breakpoint
CREATE INDEX "idx_xero_invoice_matches_status" ON "xero_invoice_matches" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_plan_working_drafts_master" ON "plan_working_drafts" USING btree ("master_id");--> statement-breakpoint
CREATE INDEX "idx_plan_working_drafts_updated" ON "plan_working_drafts" USING btree ("updated_at");