CREATE TABLE "finance_clearance_sends" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_clearance_sends_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"month" text NOT NULL,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"hash" text NOT NULL,
	"counts" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "overdue_digest_sends" (
	"as_of_date" date PRIMARY KEY NOT NULL,
	"sent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"invoice_count" integer NOT NULL,
	"total_due_cents" bigint NOT NULL,
	"recipients" text[] NOT NULL
);
--> statement-breakpoint
ALTER TABLE "finance_billing_records" ADD COLUMN "export_blob_path" text;--> statement-breakpoint
ALTER TABLE "finance_billing_records" ADD COLUMN "xero_match_resolution" text;--> statement-breakpoint
ALTER TABLE "finance_billing_records" ADD COLUMN "xero_expected_source" text;