-- ASSEMBLEDVIEW.MART.VW_PACING_FACT
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace view VW_PACING_FACT(
	CHANNEL,
	DATE_DAY,
	LINE_ITEM_ID,
	ENTITY_NAME,
	ENTITY_ID,
	CAMPAIGN_NAME,
	AMOUNT_SPENT,
	IMPRESSIONS,
	CLICKS,
	RESULTS,
	VIDEO_3S_VIEWS,
	MAX_FIVETRAN_SYNCED_AT,
	UPDATED_AT
) as
SELECT
  CHANNEL,
  DATE_DAY,
  LINE_ITEM_ID,
  ENTITY_NAME,
  ENTITY_ID,
  CAMPAIGN_NAME,
  AMOUNT_SPENT,
  IMPRESSIONS,
  CLICKS,
  RESULTS,
  VIDEO_3S_VIEWS,
  MAX_FIVETRAN_SYNCED_AT,
  UPDATED_AT
FROM ASSEMBLEDVIEW.MART.PACING_FACT;
