-- =============================================================================
-- STG_PACING.V_META_DAILY — Meta (Facebook Ads) ad-set dimensions, daily grain
-- =============================================================================
-- Schema discovery (AV_APP_READ_ROLE, 2026-04-07):
--   SHOW SCHEMAS IN DATABASE ASSEMBLEDVIEW → GOOGLE_ADS, TIKTOK_ADS, BINGADS;
--   No FACEBOOK_ADS schema in this account yet — expect Fivetran to land:
--     ASSEMBLEDVIEW.FACEBOOK_ADS.AD_INSIGHTS
--     ASSEMBLEDVIEW.FACEBOOK_ADS.AD_SET_HISTORY  (optional name fallback)
--     ASSEMBLEDVIEW.FACEBOOK_ADS.CAMPAIGN_HISTORY  (optional name fallback)
-- Adjust database/schema/table names if your connector uses a different path.
--
-- Output column list and order MUST match ASSEMBLEDVIEW.STG_PACING.V_GOOGLE_ADS_AD_GROUP_DAILY
-- exactly (UNION ALL into MART_PACING.FACT_DELIVERY_DAILY). Canonical contract:
--   DELIVERY_DATE, PLATFORM, ACCOUNT_ID, CAMPAIGN_ID, CAMPAIGN_NAME,
--   GROUP_ID, GROUP_NAME, GROUP_TYPE, SPEND, IMPRESSIONS, CLICKS,
--   CONVERSIONS, REVENUE, VIEW_THROUGH_CONVERSIONS
--
-- Meta spend is account currency (not micros). Conversions / revenue / VTC columns
-- vary by Fivetron version — tune TRY_TO_DOUBLE / source fields after first sync.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ASSEMBLEDVIEW.STG_PACING;

CREATE OR REPLACE VIEW ASSEMBLEDVIEW.STG_PACING.V_META_DAILY AS
SELECT
  COALESCE(I.DATE, I.DAY)::DATE AS DELIVERY_DATE,
  'meta'::VARCHAR(32) AS PLATFORM,
  I.ACCOUNT_ID::VARCHAR(256) AS ACCOUNT_ID,
  I.CAMPAIGN_ID::VARCHAR(256) AS CAMPAIGN_ID,
  COALESCE(CH.NAME, I.CAMPAIGN_NAME, '')::VARCHAR(2048) AS CAMPAIGN_NAME,
  COALESCE(I.ADSET_ID, I.AD_SET_ID)::VARCHAR(256) AS GROUP_ID,
  COALESCE(ASH.NAME, I.ADSET_NAME, I.AD_SET_NAME, '')::VARCHAR(2048) AS GROUP_NAME,
  'ad_set'::VARCHAR(32) AS GROUP_TYPE,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.SPEND)))::FLOAT AS SPEND,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.IMPRESSIONS)))::FLOAT AS IMPRESSIONS,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.CLICKS)))::FLOAT AS CLICKS,
  SUM(
    ZEROIFNULL(COALESCE(TRY_TO_DOUBLE(I.CONVERSIONS), TRY_TO_DOUBLE(I.RESULTS), 0))
  )::FLOAT AS CONVERSIONS,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.CONVERSION_VALUE)))::FLOAT AS REVENUE,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.VIEW_THROUGH_CONVERSIONS)))::FLOAT AS VIEW_THROUGH_CONVERSIONS
FROM ASSEMBLEDVIEW.FACEBOOK_ADS.AD_INSIGHTS I
LEFT JOIN (
  SELECT AD_SET_ID, NAME
  FROM ASSEMBLEDVIEW.FACEBOOK_ADS.AD_SET_HISTORY
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AD_SET_ID ORDER BY _FIVETRAN_SYNCED DESC NULLS LAST) = 1
) ASH
  ON ASH.AD_SET_ID = COALESCE(I.ADSET_ID, I.AD_SET_ID)
LEFT JOIN (
  SELECT CAMPAIGN_ID, NAME
  FROM ASSEMBLEDVIEW.FACEBOOK_ADS.CAMPAIGN_HISTORY
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_ID ORDER BY _FIVETRAN_SYNCED DESC NULLS LAST) = 1
) CH
  ON CH.CAMPAIGN_ID = I.CAMPAIGN_ID
GROUP BY
  1, 2, 3, 4, 5, 6, 7, 8;
