-- =============================================================================
-- STG_PACING.V_META_CAMPAIGN_DAILY — Meta campaign grain (no ad set)
-- =============================================================================
-- Use when a pacing mapping has no group_name_pattern (campaign-level pacing).
-- Same column contract as V_GOOGLE_ADS_AD_GROUP_DAILY and V_META_DAILY.
-- =============================================================================

CREATE OR REPLACE VIEW ASSEMBLEDVIEW.STG_PACING.V_META_CAMPAIGN_DAILY AS
SELECT
  COALESCE(I.DATE, I.DAY)::DATE AS DELIVERY_DATE,
  'meta'::VARCHAR(32) AS PLATFORM,
  I.ACCOUNT_ID::VARCHAR(256) AS ACCOUNT_ID,
  I.CAMPAIGN_ID::VARCHAR(256) AS CAMPAIGN_ID,
  COALESCE(CH.NAME, I.CAMPAIGN_NAME, '')::VARCHAR(2048) AS CAMPAIGN_NAME,
  I.CAMPAIGN_ID::VARCHAR(256) AS GROUP_ID,
  COALESCE(CH.NAME, I.CAMPAIGN_NAME, '')::VARCHAR(2048) AS GROUP_NAME,
  'campaign'::VARCHAR(32) AS GROUP_TYPE,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.SPEND)))::FLOAT AS SPEND,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.IMPRESSIONS)))::FLOAT AS IMPRESSIONS,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.CLICKS)))::FLOAT AS CLICKS,
  SUM(
    ZEROIFNULL(COALESCE(TRY_TO_DOUBLE(I.CONVERSIONS), TRY_TO_DOUBLE(I.RESULTS), 0))
  )::FLOAT AS CONVERSIONS,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.CONVERSION_VALUE)))::FLOAT AS REVENUE,
  SUM(ZEROIFNULL(TRY_TO_DOUBLE(I.VIEW_THROUGH_CONVERSIONS)))::FLOAT AS VIEW_THROUGH_CONVERSIONS
FROM ASSEMBLEDVIEW.FACEBOOK_ADS.AD_INSIGHTS I
LEFT JOIN (
  SELECT CAMPAIGN_ID, NAME
  FROM ASSEMBLEDVIEW.FACEBOOK_ADS.CAMPAIGN_HISTORY
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_ID ORDER BY _FIVETRAN_SYNCED DESC NULLS LAST) = 1
) CH
  ON CH.CAMPAIGN_ID = I.CAMPAIGN_ID
GROUP BY
  1, 2, 3, 4, 5, 6, 7, 8;
