-- =============================================================================
-- VW_PACING.V_DELIVERY_PACING — same dim↔fact join as FACT_LINE_ITEM_PACING_DAILY
-- =============================================================================
-- Numbered 14 (not 09) so it runs after DIM_PLAN_MAPPING gains AV_LINE_ITEM_CODE
-- (12_alter_dim_plan_mapping_add_code.sql) and after FACT_DELIVERY_DAILY exists.
--
-- Recreates the consumer view only. Other views in VW_PACING are unchanged here.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ASSEMBLEDVIEW.VW_PACING;

CREATE OR REPLACE VIEW ASSEMBLEDVIEW.VW_PACING.V_DELIVERY_PACING AS
SELECT
  m.CLIENTS_ID,
  m.AV_LINE_ITEM_ID,
  m.MEDIA_TYPE,
  m.PLATFORM,
  f.GROUP_TYPE,
  f.CAMPAIGN_NAME,
  f.GROUP_NAME,
  f.DELIVERY_DATE::DATE AS DELIVERY_DATE,
  f.SPEND * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0 AS SPEND,
  f.IMPRESSIONS * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0 AS IMPRESSIONS,
  f.CLICKS * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0 AS CLICKS,
  f.CONVERSIONS * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0 AS CONVERSIONS,
  CASE
    WHEN f.IMPRESSIONS > 0 THEN (f.CLICKS / NULLIF(f.IMPRESSIONS, 0)) * 100
    ELSE NULL
  END AS CTR,
  CASE
    WHEN f.CLICKS > 0 THEN (f.SPEND * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0) / NULLIF(f.CLICKS, 0)
    ELSE NULL
  END AS CPC,
  CASE
    WHEN f.CONVERSIONS > 0
      THEN (f.SPEND * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0) / NULLIF(f.CONVERSIONS, 0)
    ELSE NULL
  END AS CPA,
  CASE
    WHEN (f.SPEND * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0) > 0 AND f.CONVERSIONS > 0
      THEN (f.REVENUE * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0)
        / NULLIF(f.SPEND * COALESCE(m.BUDGET_SPLIT_PCT, 100) / 100.0, 0)
    ELSE NULL
  END AS ROAS,
  CAST(NULL AS FLOAT) AS TARGET_CPA,
  CAST(NULL AS FLOAT) AS TARGET_ROAS,
  CAST(NULL AS VARCHAR) AS DELIVERY_HEALTH
FROM ASSEMBLEDVIEW.MART_PACING.FACT_DELIVERY_DAILY f
INNER JOIN ASSEMBLEDVIEW.MART_PACING.DIM_PLAN_MAPPING m
  ON m.IS_ACTIVE = TRUE
  AND LOWER(TRIM(COALESCE(f.PLATFORM, ''))) = LOWER(TRIM(COALESCE(m.PLATFORM, '')))
  AND (m.START_DATE IS NULL OR f.DELIVERY_DATE::DATE >= m.START_DATE)
  AND (m.END_DATE IS NULL OR f.DELIVERY_DATE::DATE <= m.END_DATE)
  AND CASE m.MATCH_TYPE
    WHEN 'exact' THEN f.CAMPAIGN_NAME = m.CAMPAIGN_NAME_PATTERN
    WHEN 'prefix' THEN f.CAMPAIGN_NAME ILIKE m.CAMPAIGN_NAME_PATTERN || '%'
    WHEN 'regex' THEN REGEXP_LIKE(f.CAMPAIGN_NAME, m.CAMPAIGN_NAME_PATTERN, 'i')
    WHEN 'suffix_id' THEN TRUE
    ELSE FALSE
  END
  AND (
    (m.MATCH_TYPE = 'suffix_id'
      AND f.GROUP_TYPE IN ('ad_group', 'asset_group')
      AND LOWER(TRIM(REGEXP_SUBSTR(f.GROUP_NAME, '[^-]+$'))) = LOWER(TRIM(m.AV_LINE_ITEM_CODE))
    )
    OR (
      m.MATCH_TYPE <> 'suffix_id'
      AND (
        (m.GROUP_NAME_PATTERN IS NULL AND f.GROUP_TYPE = 'campaign')
        OR (m.GROUP_NAME_PATTERN IS NOT NULL AND f.GROUP_TYPE IN ('ad_group', 'asset_group'))
      )
      AND CASE m.MATCH_TYPE
        WHEN 'exact' THEN m.GROUP_NAME_PATTERN IS NULL OR f.GROUP_NAME = m.GROUP_NAME_PATTERN
        WHEN 'prefix' THEN m.GROUP_NAME_PATTERN IS NULL OR f.GROUP_NAME ILIKE m.GROUP_NAME_PATTERN || '%'
        WHEN 'regex' THEN m.GROUP_NAME_PATTERN IS NULL OR REGEXP_LIKE(f.GROUP_NAME, m.GROUP_NAME_PATTERN, 'i')
        ELSE FALSE
      END
    )
  );
