import type { SearchPacingCampaignRow, NormalisedBurst } from "@/lib/pacing/campaigns/types"
import type { SocialPacingCampaignRow } from "@/lib/pacing/social/types"
import type { ProgrammaticPacingCampaignRow } from "@/lib/pacing/programmatic/types"
import type { AdServingPacingCampaignRow } from "@/lib/pacing/ad-serving/types"
import type { DirectCampaignGroup, DirectLineItemRow } from "@/lib/pacing/direct/types"

export const LINE_AS_OF = "2026-09-16"

const BURST: NormalisedBurst = {
  index: 2,
  startDate: "2026-09-01",
  endDate: "2026-09-30",
  budget: 10_000,
  buyAmount: 10_000,
  calculatedValue: 200_000,
}

function bursts(count = 4): NormalisedBurst[] {
  return Array.from({ length: count }, (_, index) => ({
    ...BURST,
    index,
    startDate: index === 2 ? "2026-09-01" : `2026-0${index + 6}-01`,
    endDate: index === 2 ? "2026-09-30" : `2026-0${index + 6}-28`,
  }))
}

export function searchFixture(
  overrides: Partial<SearchPacingCampaignRow> = {},
): SearchPacingCampaignRow {
  return {
    mbaNumber: "jayco001",
    mediaPlanVersionId: 1,
    mediaPlanVersionNumber: 1,
    lineItemId: "jayco001se1",
    lineItemNumber: 1,
    xanoRowId: 1,
    clientName: "Jayco",
    campaignName: "Jayco AU – Annual Plan",
    campaignStatus: "booked",
    campaignStartDate: "2026-07-01",
    campaignEndDate: "2026-12-31",
    brand: null,
    platform: "Google Ads",
    bidStrategy: "tCPA",
    buyType: "cpc",
    creativeTargeting: "brand + generic RV",
    creative: "",
    buyingDemo: "",
    market: "AU",
    fixedCostMedia: false,
    clientPaysForMedia: false,
    budgetIncludesFees: true,
    lineItemStartDate: "2026-07-01",
    lineItemEndDate: "2026-12-31",
    totalLineItemBudget: 20_000,
    totalBursts: 4,
    bursts: bursts(),
    currentBurstIndex: 2,
    currentBurst: BURST,
    lineItemStatus: "ahead",
    burstDays: 30,
    burstDaysRemaining: 14,
    spendPerDayRemaining: 100,
    spendRemainingCurrentBurst: 2_000,
    spendRemainingLineTotal: 5_000,
    spendToDateLineTotal: 15_000,
    spendToDateCurrentBurst: 8_000,
    spendYesterday: 400,
    impressions: 200_000,
    clicks: 10_000,
    conversions: 200,
    revenue: 0,
    cpc: 1.5,
    ctr: 0.05,
    cpm: 75,
    kpiTargets: {
      mediaType: "search",
      publisher: "google",
      bidStrategy: "tCPA",
      ctr: 4,
      cpv: null,
      conversionRate: 1.5,
      vtr: null,
      frequency: null,
    },
    platformCampaigns: [],
    ...overrides,
  }
}

export function socialFixture(
  overrides: Partial<SocialPacingCampaignRow> = {},
): SocialPacingCampaignRow {
  return {
    mbaNumber: "jayco001",
    mediaPlanVersionId: 1,
    mediaPlanVersionNumber: 1,
    lineItemId: "jayco001so1",
    lineItemNumber: 1,
    xanoRowId: 1,
    clientName: "Jayco",
    campaignName: "Jayco Social",
    campaignStatus: "booked",
    campaignStartDate: "2026-07-01",
    campaignEndDate: "2026-12-31",
    brand: null,
    platform: "Meta",
    bidStrategy: "",
    buyType: "cpm",
    creativeTargeting: "lookalike",
    creative: "",
    buyingDemo: "",
    market: "AU",
    fixedCostMedia: false,
    clientPaysForMedia: false,
    budgetIncludesFees: true,
    socialPlatform: "meta",
    deliverableMetric: "IMPRESSIONS",
    deliverableTarget: 500_000,
    lineItemStartDate: "2026-07-01",
    lineItemEndDate: "2026-12-31",
    totalLineItemBudget: 20_000,
    totalBursts: 4,
    bursts: bursts(),
    currentBurstIndex: 2,
    currentBurst: BURST,
    lineItemStatus: "on-track",
    burstDays: 30,
    burstDaysRemaining: 14,
    spendPerDayRemaining: 100,
    spendRemainingCurrentBurst: 4_000,
    spendRemainingLineTotal: 10_000,
    spendToDateLineTotal: 8_000,
    spendToDateCurrentBurst: 4_000,
    spendYesterday: 120,
    spend: 8_000,
    impressions: 180_000,
    clicks: 3_600,
    results: 90,
    videoViews: 12_000,
    deliverableActual: 180_000,
    ctr: 0.02,
    conversionRate: 0.0005,
    cpv: 0.67,
    vtr: 0.066,
    kpiTargets: {
      mediaType: "social",
      publisher: "meta",
      bidStrategy: null,
      ctr: 2,
      cpv: null,
      conversionRate: null,
      vtr: 5,
      frequency: null,
    },
    platformCampaigns: [],
    ...overrides,
  }
}

export function programmaticFixture(
  overrides: Partial<ProgrammaticPacingCampaignRow> = {},
): ProgrammaticPacingCampaignRow {
  return {
    mbaNumber: "jayco001",
    mediaPlanVersionId: 1,
    mediaPlanVersionNumber: 1,
    lineItemId: "jayco001pd1",
    lineItemNumber: 1,
    xanoRowId: 1,
    clientName: "Jayco",
    campaignName: "Jayco Prog",
    campaignStatus: "booked",
    campaignStartDate: "2026-07-01",
    campaignEndDate: "2026-12-31",
    brand: null,
    platform: "dv360",
    platformLabel: "DV360",
    bidStrategy: "",
    buyType: "cpm",
    creativeTargeting: "prospecting",
    creative: "",
    buyingDemo: "",
    market: "AU",
    fixedCostMedia: false,
    clientPaysForMedia: false,
    budgetIncludesFees: true,
    channelFamily: "progDisplay",
    snowflakeChannel: "programmatic-display",
    deliverableMetric: "IMPRESSIONS",
    deliverableTarget: 1_000_000,
    lineItemStartDate: "2026-07-01",
    lineItemEndDate: "2026-12-31",
    totalLineItemBudget: 20_000,
    totalBursts: 4,
    bursts: bursts(),
    currentBurstIndex: 2,
    currentBurst: BURST,
    lineItemStatus: "behind",
    burstDays: 30,
    burstDaysRemaining: 14,
    spendPerDayRemaining: 200,
    spendRemainingCurrentBurst: 6_000,
    spendRemainingLineTotal: 14_000,
    spendToDateLineTotal: 6_000,
    spendToDateCurrentBurst: 2_000,
    spendYesterday: 80,
    spend: 6_000,
    impressions: 400_000,
    clicks: 2_000,
    results: 0,
    videoViews: 0,
    deliverableActual: 400_000,
    ctr: 0.005,
    conversionRate: null,
    cpm: 15,
    cpv: null,
    vtr: null,
    kpiTargets: {
      mediaType: "display",
      publisher: "dv360",
      bidStrategy: null,
      ctr: 0.6,
      cpv: null,
      conversionRate: null,
      vtr: null,
      frequency: null,
    },
    platformCampaigns: [],
    ...overrides,
  }
}

export function adServingFixture(
  overrides: Partial<AdServingPacingCampaignRow> = {},
): AdServingPacingCampaignRow {
  return {
    mbaNumber: "jayco001",
    mediaPlanVersionId: 1,
    mediaPlanVersionNumber: 1,
    lineItemId: "jayco001dd1",
    lineItemNumber: 1,
    xanoRowId: 1,
    clientName: "Jayco",
    campaignName: "Jayco Direct Digital",
    campaignStatus: "booked",
    campaignStartDate: "2026-07-01",
    campaignEndDate: "2026-12-31",
    brand: null,
    platform: "CM360",
    bidStrategy: "",
    buyType: "cpm",
    creativeTargeting: "homepage ROS",
    creative: "ROS",
    buyingDemo: "",
    market: "AU",
    channelFamily: "digitalDisplay",
    lineItemStartDate: "2026-07-01",
    lineItemEndDate: "2026-12-31",
    totalBursts: 3,
    bursts: bursts(3),
    currentBurstIndex: 2,
    currentBurst: BURST,
    lineItemStatus: "serving",
    plannedImpressions: 500_000,
    plannedClicks: 0,
    impressions: 220_000,
    clicks: 1_100,
    ctr: 0.005,
    videoCompletes: 0,
    results: 0,
    daysActive: 40,
    deliverableProgress: 0.44,
    deliverableActual: 220_000,
    deliverableTarget: 500_000,
    deliverableKind: "impressions",
    ...overrides,
  }
}

export function directLineFixture(
  overrides: Partial<DirectLineItemRow> = {},
): DirectLineItemRow {
  return {
    lineItemId: "jayco001tv1",
    mbaNumber: "jayco001",
    lineItemName: "FTA burst 3",
    buyType: "fixed_cost",
    isCurrentlyFixedCost: true,
    wasEverFixedCost: true,
    totalBudget: 40_000,
    totalReported: 18_000,
    totalActual: 16_500,
    variance: 1_500,
    variancePct: 0.083,
    burstCount: 3,
    burstsDeliveredOver: 0,
    burstsDeliveredUnder: 0,
    lineItemStatus: "in_progress",
    bursts: [
      {
        burstIndex: 1,
        startDate: "2026-07-01",
        endDate: "2026-07-31",
        budget: 12_000,
        expectedDeliverables: 0,
        actualDeliverables: 0,
        deliveryRatio: 1,
        reportedSpend: 12_000,
        actualPlatformSpend: 11_000,
        variance: 1_000,
        status: "completed",
      },
      {
        burstIndex: 2,
        startDate: "2026-09-01",
        endDate: "2026-09-30",
        budget: 14_000,
        expectedDeliverables: 0,
        actualDeliverables: 0,
        deliveryRatio: 1,
        reportedSpend: 6_000,
        actualPlatformSpend: 5_500,
        variance: 500,
        status: "in_progress",
      },
      {
        burstIndex: 3,
        startDate: "2026-11-01",
        endDate: "2026-11-30",
        budget: 14_000,
        expectedDeliverables: 0,
        actualDeliverables: 0,
        deliveryRatio: 0,
        reportedSpend: 0,
        actualPlatformSpend: 0,
        variance: 0,
        status: "pending",
      },
    ],
    daily: [],
    ...overrides,
  }
}

export function directGroupFixture(
  overrides: Partial<DirectCampaignGroup> = {},
): DirectCampaignGroup {
  const line = directLineFixture()
  return {
    mbaNumber: "jayco001",
    clientName: "Jayco",
    campaignName: "Jayco TV",
    campaignStatus: "booked",
    campaignStartDate: "2026-07-01",
    campaignEndDate: "2026-12-31",
    brand: null,
    lineItems: [line],
    totalBudget: line.totalBudget,
    totalReported: line.totalReported,
    totalActual: line.totalActual,
    variance: line.variance,
    ...overrides,
  }
}
