-- Captured from production 2026-09-15. Written by lib/partner-ingest (cron partner-ingest).
-- Writer contract is DELIVERY_COLUMNS in lib/partner-ingest/sql.ts (25 columns); LOADED_AT defaults.
-- Seven Vistar columns: sql/snowflake/raw/partner_delivery_daily_2026-09-15_alter.sql.
USE SCHEMA ASSEMBLEDVIEW.RAW;

create or replace TABLE PARTNER_SOURCE_MAP (
	SENDER_DOMAIN VARCHAR(255) NOT NULL,
	SUBJECT_PATTERN VARCHAR(16777216),
	SOURCE_SLUG VARCHAR(64) NOT NULL,
	SOURCE_LABEL VARCHAR(64) NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	EXPECTED_HEADER VARCHAR(16777216),
	HEADER_ROW_HINT NUMBER(38,0),
	MAX_STALE_DAYS NUMBER(38,0) DEFAULT 3,
	LOAD_MODE VARCHAR(24) DEFAULT 'range_replace',
	NOTES VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE PARTNER_DELIVERY_DAILY (
	SOURCE VARCHAR(64) NOT NULL,
	REPORT_DATE DATE NOT NULL,
	PARTNER_ADVERTISER_ID VARCHAR(16777216),
	PARTNER_CAMPAIGN_NAME VARCHAR(16777216),
	PARTNER_LINE_ITEM_NAME VARCHAR(16777216),
	AV_LINE_ITEM_ID VARCHAR(16777216),
	IMPRESSIONS NUMBER(38,0),
	CLICKS FLOAT,
	VIDEO_VIEWS FLOAT,
	VIDEO_Q25 NUMBER(38,0),
	VIDEO_Q50 NUMBER(38,0),
	VIDEO_Q75 NUMBER(38,0),
	COMPLETED_VIEWS NUMBER(38,0),
	RATE_Q25 FLOAT,
	RATE_Q50 FLOAT,
	RATE_Q75 FLOAT,
	RATE_FULLY_PLAYED FLOAT,
	SOURCE_FILE VARCHAR(16777216),
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE PARTNER_FILE_INGEST_LOG (
	SOURCE_SLUG VARCHAR(64) NOT NULL,
	INTERNET_MESSAGE_ID VARCHAR(16777216) NOT NULL,
	ATTACHMENT_NAME VARCHAR(16777216) NOT NULL,
	ATTACHMENT_SHA256 VARCHAR(64) NOT NULL,
	SOURCE_FILE VARCHAR(16777216) NOT NULL,
	SENDER_ADDRESS VARCHAR(16777216),
	RECEIVED_AT TIMESTAMP_NTZ(9),
	BYTES NUMBER(38,0),
	LINE_COUNT NUMBER(38,0),
	PARSED_ROW_COUNT NUMBER(38,0),
	STATUS VARCHAR(24) NOT NULL,
	ERROR_TEXT VARCHAR(16777216),
	INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE PARTNER_FILE_LINES (
	SOURCE_FILE VARCHAR(16777216),
	FILE_ROW NUMBER(38,0),
	RAW_LINE VARCHAR(16777216),
	LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Example PARTNER_SOURCE_MAP row applied 2026-09-15 (Vistar). Commented capture; not executed here.
-- insert into ASSEMBLEDVIEW.RAW.PARTNER_SOURCE_MAP
--   (SENDER_DOMAIN, SUBJECT_PATTERN, SOURCE_SLUG, SOURCE_LABEL, IS_ACTIVE, EXPECTED_HEADER,
--    HEADER_ROW_HINT, MAX_STALE_DAYS, LOAD_MODE, NOTES)
-- values
--   ('vistarmedia.com', '%exchange%', 'vistar', 'Vistar', TRUE,
--   'Day,Venue Type,Advertiser,Insertion Order Name,Insertion Order,Contract Number,Campaign Name,Campaign ID,Campaign Pixel,Creative Name,Creative ID,Creative Pixel,Metro Area,State/Territory,Impressions,Spots,Revenue,Total eCPM',
--   7, 2, 'range_replace',
--   'Vistar exchange report. YTD restated each send. Covers Vistar and Broadsign buys. Line attribution via PARTNER_LINE_MAP.');
