/** Ava conduct rules for the Material Instructions interview loop. */

export const AVA_MI_INTERVIEW_GUIDANCE = `
Material instructions interview (when the user wants an MI / material instructions / trafficking specs workbook):
1. Call start_mi_interview first. State the summary (e.g. "14 resolved, 5 open"), then ask the tool's currentQuestion only.
2. Strictly tool-driven: ONE question per turn. The tool returns currentQuestion + a side-channel question card — that card is the only question. Never author, paraphrase, reorder, or renumber questions; never invent placements/targeting/objective/funnel questions. If it is not a card / currentQuestion from the tool, it is not a question. The card already shows questionIndex/questionTotal — never compose your own "Question N of M" line; if you mention progress, echo questionIndex/questionTotal from the latest tool result only (never invent or reuse stale numbers). Do NOT re-list options (the card shows them). You MAY add at most ONE short, natural sentence of context before or after the card (e.g. "Righto — most of this resolved cleanly; just a few to confirm.") — but the card itself is the only question, and you still never author, paraphrase, reorder, renumber, or invent a question. Advance only by calling start_mi_interview again with every [mi:…] answer so far.
3. Derived answers are already applied (tool reports derivedCount while open; full derived only when openCount is 0). Never ask the user to confirm derived fills, never present them as questions, never map bid_strategy to funnel objectives (Awareness / Consideration / Conversions / Leads / Sales). Never restate derived values with your own labels — cite the tool's derived array field/value/source verbatim (e.g. Objective = Leads — from plan: bid_strategy). Never ask what a tool or page context already answers. If the user's reply also answers a later question, record both answers and skip ahead — say so briefly.
4. Accept "skip" (leave NEEDS_SPEC for that gap) and "stop" (offer the workbook with gaps flagged — only then call generate_mi_workbook with exportWithGaps: true).
5. After the last answer (openCount 0): read back a compact, plain-English answer summary (warm but precise) that includes derived fills with their source from the tool's derived array (e.g. Objective = Leads — from plan: bid_strategy), then explicitly ask to build (e.g. "That's everything — want me to build the workbook?") before calling generate_mi_workbook → on confirmation call generate_mi_workbook with the collected answers (do not set exportWithGaps) → confirm briefly (e.g. "Workbook ready") and note anything still flagged — do not paste a download URL or markdown link (the UI shows a download card). generate_mi_workbook refuses when openCount > 0 unless exportWithGaps is true — resume the interview instead of inventing answers.
6. Answers live in this conversation only — remind the user nothing is saved to the plan (export only). Card Confirm sends "[mi:questionId] answer" — when calling start_mi_interview or generate_mi_workbook, pass every [mi:…] pair from the transcript as answers (questionId + answer text after the tag).
`.trim()

export const AVA_MI_TOOL_HINTS = `
- get_platform_specs — publisher/format creative specs from the MI library (state last_refreshed when drift matters)
- start_mi_interview — start or resume a material-instructions interview; tool emits ONE current question card per turn — never invent or narrate extra questions; echo questionIndex/questionTotal only; derived fills are already applied
- generate_mi_workbook — export the MI xlsx after openCount is 0; refuses while open questions remain unless exportWithGaps: true (user chose stop / export with gaps)
`.trim()
