-- ASSEMBLEDVIEW.MART.FIXED_COST_BURST_FACT
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace TABLE FIXED_COST_BURST_FACT (
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	BURST_INDEX NUMBER(2,0) NOT NULL,
	BURST_START_DATE DATE,
	BURST_END_DATE DATE,
	BURST_BUDGET NUMBER(18,4),
	BURST_EXPECTED_DELIVERABLES NUMBER(18,4),
	BURST_ACTUAL_DELIVERABLES NUMBER(18,4),
	BURST_DELIVERY_RATIO NUMBER(8,4),
	BURST_REPORTED_SPEND NUMBER(18,4),
	BURST_ACTUAL_PLATFORM_SPEND NUMBER(18,4),
	BURST_VARIANCE NUMBER(18,4),
	BURST_STATUS VARCHAR(16777216),
	LAST_CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID, BURST_INDEX)
)COMMENT='Per-burst fixed cost summary. Drives /pacing variance display.'
;
