-- ASSEMBLEDVIEW.MART.FIXED_COST_REPORTED_DAILY_FACT
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace TABLE FIXED_COST_REPORTED_DAILY_FACT cluster by (LINE_ITEM_ID, BURST_INDEX, DATE_DAY)(
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	BURST_INDEX NUMBER(2,0) NOT NULL,
	DATE_DAY DATE NOT NULL,
	REPORTED_SPEND NUMBER(18,4),
	ACTUAL_PLATFORM_SPEND NUMBER(18,4),
	ACTUAL_DELIVERABLES NUMBER(18,4),
	EXPECTED_DAILY_DELIVERABLES NUMBER(18,4),
	BURST_BUDGET NUMBER(18,4),
	BURST_START_DATE DATE,
	BURST_END_DATE DATE,
	BUY_TYPE VARCHAR(16777216),
	BUY_AMOUNT NUMBER(18,4),
	SHARE_TODAY NUMBER(8,4),
	CAP_APPLIED VARCHAR(16777216),
	IS_SQUAREUP_DAY BOOLEAN DEFAULT FALSE,
	IS_LOCKED BOOLEAN DEFAULT FALSE,
	CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID, BURST_INDEX, DATE_DAY)
)COMMENT='Per-day fixed cost reported spend. One row per (line_item, burst, day). 3-day rolling recalculation; older days locked.'
;
