-- Captured from production 2026-09-15. Filled by SP_REFRESH_FIXED_COST_REPORTED_DAILY
-- (task TSK_REFRESH_FIXED_COST_REPORTED, after TSK_REFRESH_PACING_FACT).
-- Per-table June captures in this folder match this DDL; this file is the combined 15 Sep capture.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace TABLE FIXED_COST_REPORTED_DAILY_FACT cluster by (LINE_ITEM_ID, BURST_INDEX, DATE_DAY)(
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	BURST_INDEX NUMBER(2,0) NOT NULL,
	DATE_DAY DATE NOT NULL,
	REPORTED_SPEND NUMBER(18,4),
	ACTUAL_PLATFORM_SPEND NUMBER(18,4),
	ACTUAL_DELIVERABLES NUMBER(18,4),
	EXPECTED_DAILY_DELIVERABLES NUMBER(18,4),
	BURST_BUDGET NUMBER(18,4),
	BURST_START_DATE DATE,
	BURST_END_DATE DATE,
	BUY_TYPE VARCHAR(16777216),
	BUY_AMOUNT NUMBER(18,4),
	SHARE_TODAY NUMBER(8,4),
	CAP_APPLIED VARCHAR(16777216),
	IS_SQUAREUP_DAY BOOLEAN DEFAULT FALSE,
	IS_LOCKED BOOLEAN DEFAULT FALSE,
	CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID, BURST_INDEX, DATE_DAY)
)COMMENT='Per-day fixed cost reported spend. One row per (line_item, burst, day). 3-day rolling recalculation; older days locked.'
;

create or replace TABLE FIXED_COST_BURST_FACT (
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	BURST_INDEX NUMBER(2,0) NOT NULL,
	BURST_START_DATE DATE,
	BURST_END_DATE DATE,
	BURST_BUDGET NUMBER(18,4),
	BURST_EXPECTED_DELIVERABLES NUMBER(18,4),
	BURST_ACTUAL_DELIVERABLES NUMBER(18,4),
	BURST_DELIVERY_RATIO NUMBER(8,4),
	BURST_REPORTED_SPEND NUMBER(18,4),
	BURST_ACTUAL_PLATFORM_SPEND NUMBER(18,4),
	BURST_VARIANCE NUMBER(18,4),
	BURST_STATUS VARCHAR(16777216),
	LAST_CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID, BURST_INDEX)
)COMMENT='Per-burst fixed cost summary. Drives /pacing variance display.'
;

create or replace TABLE FIXED_COST_LINE_ITEM_FACT (
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	MBA_NUMBER VARCHAR(16777216),
	LINE_ITEM_NAME VARCHAR(16777216),
	IS_CURRENTLY_FIXED_COST BOOLEAN,
	WAS_EVER_FIXED_COST BOOLEAN,
	LINE_ITEM_TOTAL_BUDGET NUMBER(18,4),
	LINE_ITEM_TOTAL_REPORTED NUMBER(18,4),
	LINE_ITEM_TOTAL_ACTUAL NUMBER(18,4),
	LINE_ITEM_VARIANCE NUMBER(18,4),
	BURST_COUNT NUMBER(2,0),
	BURSTS_DELIVERED_OVER NUMBER(2,0),
	BURSTS_DELIVERED_UNDER NUMBER(2,0),
	LAST_CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID)
)COMMENT='Per-line-item fixed cost summary. WAS_EVER_FIXED_COST is sticky once true.'
;
