-- ASSEMBLEDVIEW.MART.FIXED_COST_LINE_ITEM_FACT
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace TABLE FIXED_COST_LINE_ITEM_FACT (
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	MBA_NUMBER VARCHAR(16777216),
	LINE_ITEM_NAME VARCHAR(16777216),
	IS_CURRENTLY_FIXED_COST BOOLEAN,
	WAS_EVER_FIXED_COST BOOLEAN,
	LINE_ITEM_TOTAL_BUDGET NUMBER(18,4),
	LINE_ITEM_TOTAL_REPORTED NUMBER(18,4),
	LINE_ITEM_TOTAL_ACTUAL NUMBER(18,4),
	LINE_ITEM_VARIANCE NUMBER(18,4),
	BURST_COUNT NUMBER(2,0),
	BURSTS_DELIVERED_OVER NUMBER(2,0),
	BURSTS_DELIVERED_UNDER NUMBER(2,0),
	LAST_CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (LINE_ITEM_ID)
)COMMENT='Per-line-item fixed cost summary. WAS_EVER_FIXED_COST is sticky once true.'
;
