-- ASSEMBLEDVIEW.MART.XANO_LINE_ITEMS_SNAPSHOT
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace TABLE XANO_LINE_ITEMS_SNAPSHOT (
	LINE_ITEM_ID VARCHAR(16777216) NOT NULL,
	MBA_NUMBER VARCHAR(16777216),
	LINE_ITEM_NAME VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	BUY_TYPE VARCHAR(16777216),
	FIXED_COST_MEDIA BOOLEAN,
	BURSTS_JSON VARIANT,
	SOURCE_TABLE VARCHAR(16777216),
	XANO_ROW_ID NUMBER(38,0),
	XANO_CREATED_AT NUMBER(38,0),
	SYNCED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (LINE_ITEM_ID)
)COMMENT='Snapshot of Xano line item data for fixed cost procedure consumption. Synced daily from Vercel cron.'
;
