export const MEDIA_TYPE_LABELS: Record<string, string> = {
  television: "Television",
  radio: "Radio",
  newspaper: "Newspaper",
  magazines: "Magazines",
  ooh: "OOH",
  cinema: "Cinema",
  digiDisplay: "Digital Display",
  digiAudio: "Digital Audio",
  digiVideo: "Digital Video",
  bvod: "BVOD",
  integration: "Integration",
  search: "Search",
  socialMedia: "Social Media",
  progDisplay: "Programmatic Display",
  progVideo: "Programmatic Video",
  progBvod: "Programmatic BVOD",
  progAudio: "Programmatic Audio",
  progOoh: "Programmatic OOH",
  influencers: "Influencers",
  production: "Production",
}

/** ARGB format (FF prefix) — used by Excel export, do NOT convert to CSS hex without auditing consumers. */
export const MEDIA_TYPE_COLORS: Record<string, string> = {
  television: "FF1565C0",
  radio: "FF6A1B9A",
  newspaper: "FF37474F",
  magazines: "FFAD1457",
  ooh: "FFE65100",
  cinema: "FFB71C1C",
  digiDisplay: "FF00695C",
  digiAudio: "FF1A237E",
  digiVideo: "FF4527A0",
  bvod: "FFF57F17",
  integration: "FF2E7D32",
  search: "FF1B5E20",
  socialMedia: "FF0D47A1",
  progDisplay: "FF263238",
  progVideo: "FF311B92",
  progBvod: "FFF9A825",
  progAudio: "FFBF360C",
  progOoh: "FF558B2F",
  influencers: "FF880E4F",
  production: "FF4E342E",
}

export const MEDIA_TYPE_KEYS: readonly string[] = Object.keys(MEDIA_TYPE_LABELS)
