-- ASSEMBLEDVIEW.MART.TSK_REFRESH_GOOGLESEARCHPACING
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace task TSK_REFRESH_GOOGLESEARCHPACING
	warehouse=AV_APP_WH
	after ASSEMBLEDVIEW.MART.TSK_ROOT_DAILY_REFRESH
	as call ASSEMBLEDVIEW.MART.SP_REFRESH_GOOGLESEARCHPACING_ROLLING(14);
