-- ASSEMBLEDVIEW.MART.TSK_REFRESH_FIXED_COST_REPORTED
-- Captured from Snowflake GET_DDL on 2026-06-08. Source of truth.
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace task TSK_REFRESH_FIXED_COST_REPORTED
	warehouse=AV_APP_WH
	after ASSEMBLEDVIEW.MART.TSK_REFRESH_GOOGLESEARCHPACING, ASSEMBLEDVIEW.MART.TSK_REFRESH_PACING_FACT, ASSEMBLEDVIEW.MART.TSK_REFRESH_SOCIAL_PACING_FACT
	as CALL ASSEMBLEDVIEW.MART.SP_REFRESH_FIXED_COST_REPORTED_DAILY(NULL, FALSE);
