-- ASSEMBLEDVIEW.MART.TSK_REFRESH_FIXED_COST_REPORTED
-- Live DDL captured 2026-09-15 (GET_DDL, ACCOUNTADMIN). Runs after the three fact refreshes.
-- Args: (LINE_ITEM_ID_FILTER NULL = all lines, BACKFILL_MODE FALSE = 3-day rolling window).
USE SCHEMA ASSEMBLEDVIEW.MART;

create or replace task TSK_REFRESH_FIXED_COST_REPORTED
	warehouse=AV_APP_WH
	after ASSEMBLEDVIEW.MART.TSK_REFRESH_GOOGLESEARCHPACING, ASSEMBLEDVIEW.MART.TSK_REFRESH_PACING_FACT, ASSEMBLEDVIEW.MART.TSK_REFRESH_SOCIAL_PACING_FACT
	as CALL ASSEMBLEDVIEW.MART.SP_REFRESH_FIXED_COST_REPORTED_DAILY(NULL, FALSE);
