import * as z from "zod"

const clientSchema = z.object({
  id: z.number(),
  clientname_input: z.string().min(1, "Client name is required"),
  clientcategory: z.string().min(1, "Client category is required"),
  abn: z.number().int().positive(),
  mbaidentifier: z.string(),
  legalbusinessname: z.string().min(1, "Legal business name is required"),
  streetaddress: z.string().min(1, "Street address is required"),
  suburb: z.string().min(1, "Suburb is required"),
  state_dropdown: z.enum(["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]),
  postcode: z.number().int().min(1000).max(9999),
  keyfirstname: z.string().min(1, "Key contact first name is required"),
  keylastname: z.string().min(1, "Key contact last name is required"),
  keyphone: z.number().int().positive(),
  keyemail: z.string().email(),
  billingfirstname: z.string().min(1, "Billing contact first name is required"),
  billinglastname: z.string().min(1, "Billing contact last name is required"),
  billingphone: z.number().int().positive(),
  billingemail: z.string().email(),
  monthlyretainer: z.number().nonnegative(),
  organicsocial: z.number().nonnegative(),
  television_checkbox: z.boolean(),
  radio_checkbox: z.boolean(),
  newspapers_checkbox: z.boolean(),
  magazines_checkbox: z.boolean(),
  ooh_checkbox: z.boolean(),
  cinema_checkbox: z.boolean(),
  digitaldisplay_checkbox: z.boolean(),
  digitalaudio_checkbox: z.boolean(),
  digitalvideo_checkbox: z.boolean(),
  bvod_checkbox: z.boolean(),
  feesocial: z.number().nonnegative(),
  feesearch: z.number().nonnegative(),
  feeprogdisplay: z.number().nonnegative(),
  feeprogvideo: z.number().nonnegative(),
  feeprogbvod: z.number().nonnegative(),
  feeprogaudio: z.number().nonnegative(),
  feeprogooh: z.number().nonnegative(),
  feecontentcreator: z.number().nonnegative(),
  adservvideo: z.number().nonnegative(),
  adservimp: z.number().nonnegative(),
  adservdisplay: z.number().nonnegative(),
  adservaudio: z.number().nonnegative(),
  idgoogleads: z.string(),
  idmeta: z.string(),
  idcm360: z.string(),
  iddv360: z.string(),
  idtiktok: z.string(),
  idlinkedin: z.string(),
  idpinterest: z.string(),
  idquantcast: z.string(),
  idtaboola: z.string(),
  idsnapchat: z.string(),
  idbing: z.string(),
  idvistar: z.string(),
  idga4: z.string(),
  idmerchantcentre: z.string(),
  idshopify: z.string(),
})

export const clientSchema = clientSchema

